import { Game, freshState, migrateState, validateState, statsFor, clamp } from './engine.js?v=growth-1';
const $=id=>document.getElementById(id);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const KEY='pokedays-hgss-v1';
const typeColors={1:['#e9e6de','#928978'],2:['#f3ddd5','#b67868'],3:['#e5e6f9','#8f8dbe'],4:['#eadff0','#a47ab6'],5:['#ede3cf','#b29660'],6:['#e7e1ce','#a09565'],7:['#e8edd1','#97a556'],8:['#e9e1f2','#9780ac'],9:['#e1e5e9','#8c99a3'],10:['#f9e3d4','#c98e62'],11:['#dfeef7','#7bacc5'],12:['#e4efd8','#8ea569'],13:['#fcf0ce','#bea252'],14:['#f6dfe8','#bd89a0'],15:['#dff1ef','#86b1ae'],16:['#e6def5','#9581b9'],17:['#e7e1dd','#94867a']};
let db,game,busy=false,required=false,toastTimer,saveWarning=null;
const badge=t=>`<span class="type-badge" style="--type-bg:${typeColors[t]?.[0]};--type-ink:${typeColors[t]?.[1]}">${esc(db.types[t].name)}</span>`;
const petSprite=(id,back=false)=>`assets/sprites/${id}${back?'-back':''}.png`;
function save(){try{localStorage.setItem(KEY,JSON.stringify(game.s));$('save-status').textContent='이 브라우저에 자동 저장';}catch{$('save-status').textContent='저장 불가 · 백업을 내려받으세요';saveWarning='브라우저 저장을 사용할 수 없어요. 아래 저장 백업으로 진행 상황을 보관하세요.';}}
function say(text){$('message').textContent=text;}
function speak(text){$('speech').textContent=text;}
function modal(html,tag='POKÉ DAYS',mustChoose=false){required=mustChoose;$('modal-tag').textContent=tag;$('modal-body').innerHTML=html;$('close-modal').hidden=mustChoose;if(!$('modal').open)$('modal').showModal();$('modal').scrollTop=0;}
function closeModal(){if(required)return;$('modal').close();}
$('close-modal').onclick=closeModal;$('modal').addEventListener('cancel',e=>{if(required)e.preventDefault();});$('modal').addEventListener('click',e=>{if(e.target===$('modal')&&!required){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function render(){
  $('egg-screen').hidden=game.s.hatched;$('pet-game').hidden=!game.s.hatched;
  if(!game.s.hatched){renderEgg();return;}
  const s=game.s,p=game.pet,sp=game.species,stat=statsFor(db,p.speciesId,p.level,p.ivs),inBattle=!!s.battle;
  $('day').textContent='DAY '+String(s.day).padStart(2,'0');
  $('roster').innerHTML=[s.active].map(id=>{const q=s.pets[id],spec=db.pokemon[q.speciesId];return `<button data-pet="${id}" class="${s.active===id?'active':''}" aria-pressed="${s.active===id}" ${busy||!game.ready()?'disabled':''}><img src="${petSprite(q.speciesId)}" alt=""><span><strong>${esc(spec.name)}</strong><small>Lv. ${q.level}${s.active===id?' · 함께하는 중':''}</small></span></button>`;}).join('');
  $('roster').querySelectorAll('[data-pet]').forEach(b=>b.onclick=()=>{if(game.switch(Number(b.dataset.pet))){save();render();speak('오늘은 나랑 같이 놀자!');say(`${game.species.name}와 함께할 준비가 됐어요. 무엇을 할까요?`);}});
  $('pet').src=petSprite(p.speciesId,inBattle);$('pet').alt=sp.name;
  $('pet-name').textContent=sp.name;$('level').textContent='Lv. '+p.level;$('dex-no').textContent='NO.'+String(p.speciesId).padStart(3,'0');$('pet-nameplate').innerHTML=esc(sp.name)+` <span>Lv.${p.level}</span>`;
  $('types').innerHTML=sp.typeIds.map(badge).join('');
  const floor=db.experience[sp.growthRateId][p.level],next=game.nextXp();$('xp-text').textContent=next===null?'MAX LEVEL':Math.max(0,next-p.exp).toLocaleString()+' EXP';$('xp-bar').style.width=(next===null?100:clamp((p.exp-floor)/(next-floor)*100,0,100))+'%';
  $('vitals').innerHTML=[['hp','♥ 체력',p.hp,stat.hp],['hunger','♨ 포만감',p.hunger,100],['friend','♡ 친밀도',p.friendship,255]].map(([cls,label,v,max])=>`<div class="vital ${cls}"><span>${label}</span><strong>${v} / ${max}</strong><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join('');
  $('fatigue-text').textContent=s.fatigue+' / 100';$('fatigue-bar').style.width=s.fatigue+'%';$('coins').textContent=s.coins.toLocaleString()+' P';
  $('move-count').textContent=p.moves.length+' / 4';$('moves').innerHTML=Array.from({length:4},(_,i)=>{const m=db.moves[p.moves[i]];return m?`<div class="move"><div><strong>${esc(m.name)}</strong><small>${m.damageClass==='status'?'변화':m.damageClass==='physical'?'물리':'특수'} · 위력 ${m.power??'—'} · PP ${m.pp}</small></div>${badge(m.typeId)}</div>`:`<div class="move empty">${i+1} · 아직 비어 있어요</div>`;}).join('');
  renderEvolutions();$('release-pet').disabled=busy||!game.ready();$('release-pet').onclick=confirmNewEgg;
  $('journal').innerHTML=s.journal.slice(0,4).map(j=>`<div class="journal-entry"><span>DAY ${j.day}</span><span>${esc(j.text)}</span></div>`).join('');
  $('battle').disabled=busy||!!game.can('battle');$('feed').disabled=busy||!!game.can('feed');$('sleep').disabled=busy||!!game.can('sleep');
  $('battle').title=game.can('battle')||'피로 35 · 포만감 18 소모';$('feed').title=game.can('feed')||'피로 15 · 포만감 35, 친밀도 12 회복';
  $('actions').hidden=inBattle;$('battle-controls').hidden=!inBattle;$('enemy').hidden=!inBattle;$('enemy-card').hidden=!inBattle;$('battle-player-hp').hidden=!inBattle;
  $('scene').classList.toggle('fighting',inBattle);$('location').textContent=inBattle?'풀숲에서 만난 친구':'초록빛 쉼터';$('weather').textContent=inBattle?'TRAINING BATTLE':'맑음 · 산들바람';
  $('action-title').textContent=inBattle?'어떤 기술을 사용할까?':'함께 할 일';$('action-caption').textContent=inBattle?`TURN ${s.battle.turn} · PP는 전투마다 회복`:'행동은 한 번에 하나씩';
  for(const id of ['dex-button','learnset','help','sources'])$(id).disabled=busy||s.pending.length>0||s.progressing;$('export-save').disabled=busy||!game.ready();
  if(inBattle)renderBattle();
}
const evolutionLocations={8:'영원의숲 · 이끼 낀 바위',10:'천관산 · 특수 자기장',48:'217번도로 · 얼음 바위'};
function evolutionText(e){
 if(e.trigger==='use-item')return esc(e.itemName)+' 사용';
 if(e.trigger==='trade')return `${esc(e.heldItemName??'도구 없이')} 지닌 채 교환`;
 if(e.locationId)return `${esc(evolutionLocations[e.locationId]??e.locationName)} 근처에서 레벨업 (D/P/Pt 조건)`;
 if(e.minFriendship)return `친밀도 ${e.minFriendship} 이상${e.timeOfDay?' · '+(e.timeOfDay==='day'?'낮':'밤'):''}에 레벨업`;
 const relation={1:'공격 > 방어','-1':'공격 < 방어',0:'공격 = 방어'};
 return `레벨 ${e.minLevel} 이상${e.relativePhysicalStats!==null&&e.relativePhysicalStats!==undefined?' · '+relation[e.relativePhysicalStats]:''}에서 레벨업`;
}
function renderEvolutions(){
 const p=game.pet,evos=game.species.evolutions,disabled=busy||!game.ready();
 $('evolution').innerHTML=evos.length?evos.map(e=>`<div class="evo-preview"><img class="pixel" src="${petSprite(e.to)}" alt="${esc(db.pokemon[e.to].name)}"><div><strong>${esc(db.pokemon[e.to].name)}</strong><p>${evolutionText(e)}</p></div></div>${e.trigger==='use-item'||e.trigger==='trade'?`<button class="evo-button" data-evolve="${e.to}" ${disabled?'disabled':''}>${e.trigger==='trade'?'도구 준비·NPC 교환':'진화의돌 구매·사용'} · 300 P</button>`:''}`).join(''):'<p class="complete">✦ 마지막 진화에 도달했어요.<br>우리의 모험은 계속돼요!</p>';
 if(evos.some(e=>e.timeOfDay||e.locationId)){
  const c=game.s.evolutionContext??{timeOfDay:'day',locationId:null};
  $('evolution').innerHTML+=`<div class="evo-context"><label>모험 시간<select id="evo-time" ${disabled?'disabled':''}><option value="day" ${c.timeOfDay==='day'?'selected':''}>낮</option><option value="night" ${c.timeOfDay==='night'?'selected':''}>밤</option></select></label><label>진화 여행지<select id="evo-place" ${disabled?'disabled':''}><option value="" ${c.locationId===null?'selected':''}>초록빛 쉼터</option>${Object.entries(evolutionLocations).map(([id,label])=>`<option value="${id}" ${c.locationId===Number(id)?'selected':''}>${label}</option>`).join('')}</select></label><p>선택한 환경에서 다음 레벨업 때 진화를 확인해요. 신오 여행지는 D/P/Pt의 조건을 이 게임에 옮긴 장소입니다.</p></div>`;
  const change=()=>{game.setEvolutionContext($('evo-time').value,$('evo-place').value?Number($('evo-place').value):null);save();render();};$('evo-time').onchange=change;$('evo-place').onchange=change;
 }
 if(p.speciesId===236){const st=statsFor(db,p.speciesId,p.level,p.ivs);$('evolution').innerHTML+=`<p class="modal-copy">현재 공격 <strong>${st.attack}</strong> · 방어 <strong>${st.defense}</strong><br>태어날 때 정해진 능력치를 바탕으로, 레벨업 후 두 수치를 비교해 진화해요.</p>`;}
 $('evolution').querySelectorAll('[data-evolve]').forEach(b=>b.onclick=()=>confirmStone(Number(b.dataset.evolve)));
}

function hpCard(f){const sp=db.pokemon[f.speciesId],status={sleep:'잠듦',paralysis:'마비',burn:'화상',poison:'독',freeze:'얼음'};return `<strong>${esc(sp.name)}</strong><small>Lv.${f.level}</small><div class="bar"><i style="width:${f.hp/f.maxHp*100}%;background:${f.hp/f.maxHp<.25?'#cd8b7e':'#8fb574'}"></i></div><span class="hp-num">${status[f.status]||''} ${f.hp} / ${f.maxHp}</span><div class="types">${game.fighterTypes(f).map(badge).join('')}</div>`;}
function renderBattle(){const b=game.s.battle;if(!b)return;$('enemy').src=petSprite(b.enemy.speciesId);$('enemy').alt=db.pokemon[b.enemy.speciesId].name;$('enemy-card').innerHTML=hpCard(b.enemy);$('battle-player-hp').innerHTML=hpCard(b.player);
  $('battle-moves').innerHTML=b.player.moves.map(slot=>{const m=db.moves[slot.id];return `<button class="battle-move" data-move="${slot.id}" ${busy||slot.pp<=0?'disabled':''}><strong>${esc(m.name)}</strong> ${badge(m.typeId)}<small>위력 ${m.power??'—'} · 명중 ${m.accuracy??'필중'} · PP ${slot.pp}/${b.player.transformed?5:m.pp}</small><small>${game.moveMatchup(m,b.player,b.enemy)}</small></button>`;}).join('');
  if(!game.usable(b.player).length)$('battle-moves').innerHTML+='<button class="battle-move" data-move="-1" '+(busy?'disabled':'')+'><strong>발버둥</strong><small>PP가 모두 소진되었어요. 사용 후 반동 피해</small></button>';
  $('battle-moves').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>turn(Number(b.dataset.move)));$('flee').disabled=busy;
}
async function care(action){if(busy)return;try{const error=game.can(action);if(error){say(error);return;}busy=true;game[action]();save();render();
  if(action==='feed'){$('pet').classList.add('eating');$('action-fx').textContent='♥';speak('냠냠! 정말 맛있어.');say('포만감 +35 · HP 30% 회복 · 친밀도 +12. 기분 좋은 식사예요.');await wait(1300);$('pet').classList.remove('eating');}
  else{$('scene').classList.add('resting');$('pet').classList.add('sleeping');$('action-fx').textContent='z Z';speak('쿨쿨… 내일도 함께 놀자.');say('친구가 잠들었어요. 하루의 피로를 푹 쉬며 회복해요.');await wait(1600);$('scene').classList.remove('resting');$('pet').classList.remove('sleeping');speak('잘 잤다! 새로운 하루야.');say(`DAY ${game.s.day}. 피로도 0, 친구의 HP가 회복됐어요. 오늘은 뭘 할까요?`);}
  $('action-fx').textContent='';busy=false;render();}catch(e){busy=false;say(e.message);render();}}
function startBattle(){if(busy)return;try{game.startBattle();save();render();say(`야생 ${db.pokemon[game.s.battle.enemy.speciesId].name}가 나타났어요! 사용할 기술을 선택하세요.`);}catch(e){say(e.message);}}
async function turn(moveId){if(busy||!game.s.battle)return;busy=true;render();try{const out=game.act(moveId);save();for(const event of out.events){const el=event.who==='player'?$('pet'):$('enemy'),target=event.who==='player'?$('enemy'):$('pet');el.classList.add('attacking');await wait(220);el.classList.remove('attacking');if(event.damage){target.classList.add('hurt');$('action-fx').textContent='−'+event.damage;await wait(220);target.classList.remove('hurt');}}
  $('action-fx').textContent='';busy=false;render();say(out.logs.join(' '));if(out.result){speak(out.result==='win'?'우리 정말 잘했어!':'조금 쉬었다 다시 해보자.');await wait(500);pump();}}catch(e){busy=false;render();say(e.message);}}
function pump(){const event=game.s.pending[0]??(game.s.progressing?game.progress():null);save();render();if(!event){if(required){required=false;$('modal').close();}return;}
  if(event.kind==='move'){const m=db.moves[event.moveId],p=game.pet;modal(`<h2 class="modal-title">새로운 기술을 배울 수 있어요!</h2><p class="modal-copy">${esc(game.species.name)}가 레벨 ${event.level}에 도달했어요.<br>기술은 최대 4개까지 기억할 수 있어요.</p><div class="new-move"><strong>${esc(m.name)}</strong> ${badge(m.typeId)}<p>위력 ${m.power??'—'} · 명중 ${m.accuracy??'필중'} · PP ${m.pp}</p></div>${p.moves.length<4?'<button class="primary" id="learn-new">빈 칸에 배우기</button>':'<p class="modal-copy">어떤 기술을 잊을까요?</p><div class="learn-options">'+p.moves.map((id,i)=>`<button data-replace="${i}">${esc(db.moves[id].name)}<br><small>이 기술 대신 배우기</small></button>`).join('')+'</div>'}<div class="modal-actions"><button class="secondary" id="skip-move">이번에는 배우지 않기</button></div>`,'NEW MOVE',true);
    const choose=i=>{game.chooseMove(i);pump();};if($('learn-new'))$('learn-new').onclick=()=>choose(0);$('modal-body').querySelectorAll('[data-replace]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.replace)));$('skip-move').onclick=()=>choose(null);
  }else{modal(`<h2 class="modal-title">어라? ${esc(game.species.name)}의 모습이…</h2><div class="evolve-art"><img class="pixel" src="${petSprite(event.from)}" alt="${esc(db.pokemon[event.from].name)}"><span>→</span><img class="pixel" src="${petSprite(event.to)}" alt="${esc(db.pokemon[event.to].name)}"></div><p class="modal-copy">${esc(db.pokemon[event.to].name)}로 진화할 준비가 됐어요.<br>지금 알고 있는 기술은 유지돼요. 진화 후에는 새로운 종의 기술표를 따라요.</p><div class="modal-actions"><button class="primary" id="accept-evo">진화하기</button><button class="secondary" id="defer-evo">다음 레벨에</button></div>`,'A LITTLE BIGGER',true);
    $('accept-evo').onclick=()=>{game.chooseEvolution(true);pump();speak('더 멋진 모습으로 함께할게!');};$('defer-evo').onclick=()=>{game.chooseEvolution(false);pump();};}}
function confirmStone(to){
 if(!game.ready()||busy)return;const e=game.species.evolutions.find(e=>e.to===to);if(!e)return;
 const trade=e.trigger==='trade',label=trade?'NPC 교환소':'진화의돌';
 modal(`<h2 class="modal-title">${esc(db.pokemon[e.to].name)}로 진화할까요?</h2><div class="evolve-art"><img class="pixel" src="${petSprite(game.pet.speciesId)}" alt=""><span>→</span><img class="pixel" src="${petSprite(e.to)}" alt=""></div><p class="modal-copy">${trade?`300 P로 ${esc(e.heldItemName??'교환 도구')}을 준비해 지니게 하고 NPC와 교환합니다. 같은 친구를 진화한 모습으로 돌려받으며 도구는 소모됩니다. 실제 사용자 간 통신 교환은 아닙니다.`:`300 P로 ${esc(e.itemName)}을 구매해 사용합니다.`}<br>진화는 되돌릴 수 없어요. 기술표를 먼저 확인해 보세요.</p><div class="modal-actions"><button id="confirm-stone" class="primary" ${game.s.coins<300?'disabled':''}>진화 진행 · 300 P</button><button id="cancel-stone" class="secondary">나중에</button></div>`,label);
 $('cancel-stone').onclick=closeModal;$('confirm-stone').onclick=()=>{try{trade?game.trade(e.to):game.stone(e.to);save();closeModal();render();say(game.s.journal[0].text);}catch(error){say(error.message);}};
}

function showDex(id=game.pet.speciesId){const sp=db.pokemon[id];modal(`<div class="modal-pet"><img class="pixel" src="${petSprite(id)}" alt="${esc(sp.name)}"><div><p class="eyebrow">NO.${String(id).padStart(3,'0')} · ${esc(sp.genus)}</p><h2>${esc(sp.name)}</h2>${sp.typeIds.map(badge).join(' ')}</div></div><p class="modal-copy">${esc(sp.description)}<br><small>도감 설명 출처 버전: ${esc(sp.descriptionVersion||'PokeAPI')}</small></p><div class="dex-stats"><div><small>키</small><strong>${sp.heightM} m</strong></div><div><small>몸무게</small><strong>${sp.weightKg} kg</strong></div><div><small>기준 버전</small><strong style="font-size:12px">HG / SS</strong></div></div><p class="modal-copy">기본 능력치 · 4세대 기준</p><div class="dex-stats">${Object.entries(sp.stats).map(([k,v])=>`<div><small>${{'hp':'HP','attack':'공격','defense':'방어','special-attack':'특수공격','special-defense':'특수방어','speed':'스피드'}[k]}</small><strong>${v}</strong></div>`).join('')}</div><h3 style="font-size:15px">함께 자라는 모습</h3><div style="display:flex;gap:8px;flex-wrap:wrap">${sp.family.map(i=>`<button class="secondary" data-dex="${i}" style="padding:7px"><img class="pixel" src="${petSprite(i)}" alt="" width="55" height="55"><br>${esc(db.pokemon[i].name)}</button>`).join('')}</div><p class="modal-copy">${sp.evolutions.map(e=>`${esc(db.pokemon[e.to].name)}: ${evolutionText(e)}`).join('<br>')||'최종 진화형입니다.'}</p><button class="primary" id="dex-learnset">레벨별 기술표 보기</button>`,'POKÉDEX · HEARTGOLD / SOULSILVER');$('modal-body').querySelectorAll('[data-dex]').forEach(b=>b.onclick=()=>showDex(Number(b.dataset.dex)));$('dex-learnset').onclick=()=>showLearnset(id);}
function showLearnset(id=game.pet.speciesId){const sp=db.pokemon[id],p=game.pet;modal(`<h2 class="modal-title">${esc(sp.name)}의 기술 노트</h2><p class="modal-copy">하트골드·소울실버의 <strong>레벨업 기술</strong>입니다.<br>현재 종이 이미 배울 수 있는 기술은 무료로 다시 떠올릴 수 있어요. 기술머신·교배 기술은 포함하지 않습니다.</p><table class="data-table"><thead><tr><th>레벨</th><th>기술 / 타입</th><th>위력</th><th>명중</th><th>PP</th><th></th></tr></thead><tbody>${sp.learnset.map(l=>{const m=db.moves[l.moveId],known=id===p.speciesId&&p.moves.includes(m.id),can=id===p.speciesId&&l.level<=p.level&&!known&&game.ready();return `<tr class="${id===p.speciesId&&l.level<=p.level?'available':''}"><td>${l.level===0?'진화':l.level===1?'기본':l.level}</td><td>${esc(m.name)}<br>${badge(m.typeId)}</td><td>${m.power??'—'}</td><td>${m.accuracy??'—'}</td><td>${m.pp}</td><td>${known?'<small>사용 중</small>':can?`<button class="text-btn" style="color:#8c63b4" data-recall="${m.id}">떠올리기</button>`:''}</td></tr>`;}).join('')}</tbody></table><p class="modal-copy">본 게임의 1:1 전투는 날씨·교체·일부 부가 효과를 간소화합니다. 레벨별 습득 조건과 기술 4칸 제한은 유지됩니다.</p>`,'MOVE NOTE');$('modal-body').querySelectorAll('[data-recall]').forEach(b=>b.onclick=()=>recallDialog(Number(b.dataset.recall)));}
function recallDialog(id){const p=game.pet,m=db.moves[id];if(p.moves.length<4){game.recall(id,0);save();render();showLearnset();return;}modal(`<h2 class="modal-title">${esc(m.name)} 떠올리기</h2><p class="modal-copy">새 기술을 위해 잊을 기술을 선택하세요.</p><div class="learn-options">${p.moves.map((mid,i)=>`<button data-slot="${i}">${esc(db.moves[mid].name)}</button>`).join('')}</div><div class="modal-actions"><button class="secondary" id="back-learnset">돌아가기</button></div>`,'MOVE REMINDER');$('modal-body').querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{game.recall(id,Number(b.dataset.slot));save();render();showLearnset();});$('back-learnset').onclick=()=>showLearnset();}
function showHelp(){modal(`<h2 class="modal-title">작은 친구와 보내는 하루</h2><div class="modal-copy"><p>처음 만나는 알을 클릭하면 미뇽 1%, 이브이 5%, 나머지 13종은 합계 94%를 같은 비율로 나누어 부화해요. 부화한 친구 한 마리만 레벨 10부터 키우며, 전투·밥먹기·잠자기 중 하나를 선택하세요. 새로고침해도 친구는 바뀌지 않아요.</p><ul><li><strong>전투</strong>: 피로 +35, 포만감 −18. 기술을 선택하는 턴제 전투예요. 승리하면 경험치와 80 P를 얻어요.</li><li><strong>밥먹기</strong>: 피로 +15. 포만감 +35, HP 30% 회복, 친밀도 +12.</li><li><strong>잠자기</strong>: 다음 게임 날로 넘어가요. 피로가 0이 되고 친구의 HP가 회복돼요. 포만감 −12, 친밀도 +3.</li></ul><p><strong>알에서 만난 친구와 계속 함께해요.</strong> 놓아주기를 선택하면 현재 육성 전체를 초기화하고 새 알을 받을 수 있어요. 확인 전 백업도 가능합니다. 실제 날짜를 기다리는 게임이 아니므로 편하게 이어서 플레이하세요.</p><p>기술은 최대 4개. 다섯 번째 기술을 배우면 하나를 잊거나 학습을 건너뛰세요. 레벨별 기술표에서 현재 종의 지나간 기술을 무료로 떠올릴 수 있어요.</p><p>삐·푸푸린은 친밀도 220 이상에서 <strong>레벨업</strong>하면 진화해요. 피카츄는 천둥의돌이 필요해요. 돌은 300 P로 구매하면서 바로 사용할 수 있어요.</p><p>이 브라우저에 자동 저장됩니다. 기기 간 동기화는 하지 않아요. 저장 백업을 내려받아 보관할 수 있습니다.</p></div><button class="secondary" id="new-egg">놓아주고 새 알 받기</button><br><label class="import-label">저장 백업 불러오기<input id="import-save" type="file" accept="application/json,.json" hidden></label><p id="import-message" class="modal-copy"></p>`,'HOW TO PLAY');$('import-save').onchange=importSave;$('new-egg').onclick=confirmNewEgg;}
function showSources(){modal(`<h2 class="modal-title">실제 데이터, 작은 게임의 규칙</h2><div class="modal-copy"><p><strong>데이터 기준: 하트골드·소울실버 / 4세대.</strong><br>야생 상대 ${db.enemyIds.length}종 / 전체 데이터 ${Object.keys(db.pokemon).length}종, ${Object.keys(db.moves).length}개 기술을 JSON으로 저장했습니다.</p><p>레벨업 기술표는 해당 버전의 데이터만 사용해요. 타입·종족값·기술의 위력/명중/PP는 과거 변경 내역을 반영했습니다. 친밀도 진화 기준은 당시의 220을 적용합니다. 따라서 삐·푸푸린 계열은 이 버전에서 노말타입입니다.</p><p>피로도·식사·수면·포인트와 경험치 보상은 이 게임만의 육성 규칙이에요. 배루키 계열은 부화 때 정한 공격·방어 개체값을 반영합니다. 나머지 개체값·노력치·성격·특성·전투 도구는 간소화합니다. 교환 진화용 도구는 NPC 교환소에서 준비합니다. 날씨·교체·일부 부가 효과는 간소화되며, 해당 기술 사용 시 안내됩니다. PP는 전투를 시작할 때 회복됩니다.</p><p>야생 상대는 전설·환상 5종을 제외한 1세대 146종입니다. 상대 레벨은 내 친구보다 0~2 낮아요. 3단계 계열은 미진화 → 20 이상 중간 → 36 이상 최종 순서이며 실제 진화 최소 레벨보다 일찍 등장하지 않습니다. 2단계 계열은 중간 단계를 건너뛰고 36 이상에 최종형이 나옵니다. 진화 없는 종은 20 이상, 종족값 합계 450 이상인 종은 30 이상에 등장합니다. 이는 이 게임의 등장 규칙이며 내 친구의 실제 진화 조건은 그대로입니다.</p><p>공격 기술 타입과 상대의 모든 타입을 곱해 0·¼·½·1·2·4배 상성을 적용합니다. 같은 타입 기술은 추가로 1.5배입니다. 고정 피해는 타입 무효만 적용하고 배율 보너스는 받지 않습니다. 발버둥은 타입 상성과 같은 타입 보너스를 받지 않습니다.</p><p>PokeAPI는 커뮤니티 데이터베이스이며 Pokémon의 공식 API는 아닙니다.</p><ul>${db.meta.sources.map(x=>`<li><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.name)}</a></li>`).join('')}</ul><p>캐릭터 스프라이트 출처: PokeAPI sprites / HGSS. 배경: AI로 제작한 픽셀 풍경.<br>Pokémon 및 캐릭터의 권리는 각 권리자에게 있습니다.</p><p><a href="data/pokedex.json" download>도감·기술·진화 JSON 다운로드 ↓</a></p></div>`,'DATA & CREDITS');}
function exportSave(){if(!game.ready()||busy)return;download(JSON.stringify(game.s,null,2),`pokedays-day-${game.s.day}.json`);say('저장 백업을 내려받았어요. 게임 안내에서 다시 불러올 수 있어요.');}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importSave(e){const file=e.target.files[0];if(!file)return;try{if((game.s.hatched&&!game.ready())||busy)throw Error('현재 전투 또는 성장을 먼저 마쳐주세요.');if(file.size>2000000)throw Error('저장 파일이 너무 큽니다.');const state=migrateState(db,validateState(db,JSON.parse(await file.text())));modal(`<h2 class="modal-title">저장한 하루로 돌아갈까요?</h2><p class="modal-copy">DAY ${state.day}의 저장을 불러옵니다. 현재 이 브라우저의 진행 상황을 덮어씁니다.</p><div class="modal-actions"><button class="primary" id="confirm-import">불러오기</button><button class="secondary" id="cancel-import">취소</button></div>`,'LOAD SAVE');$('confirm-import').onclick=()=>{game=new Game(db,state);save();closeModal();render();say(`DAY ${state.day}의 저장을 불러왔어요.`);};$('cancel-import').onclick=closeModal;}catch(err){$('import-message').textContent=err.message;}}
function renderEgg(){
  $('day').textContent='DAY 01';$('help').disabled=busy;$('sources').disabled=busy;$('export-save').disabled=true;
  $('hatch-egg').disabled=busy;$('hatch-egg').onclick=hatchEgg;
}
async function hatchEgg(){
  if(busy||game.s.hatched)return;
  busy=true;game.hatch();save(); // Commit the random result before any animation, including refreshes.
  $('hatch-egg').disabled=true;$('help').disabled=true;$('sources').disabled=true;
  $('hatch-egg').classList.add('hatching');$('hatch-hint').textContent='어라? 알이 움직이고 있어요…';
  await wait(1500);
  $('hatch-egg').classList.remove('hatching');busy=false;render();
  speak('반가워! 앞으로 잘 부탁해.');say(game.s.journal[0].text);
  modal(`<div class="hatch-reveal"><p class="eyebrow">${game.pet.speciesId===147?'RARE FRIEND · 1%':game.pet.speciesId===133?'RARE FRIEND · 5%':'HELLO, LITTLE FRIEND'}</p><img class="pixel" src="${petSprite(game.pet.speciesId)}" alt="${esc(game.species.name)}"><h2 class="modal-title">${esc(game.species.name)}가 태어났어요!</h2><p class="modal-copy">이제 이 친구와 함께 먹고, 쉬고, 모험해요.<br>둘만의 첫날을 시작해 볼까요?</p><button class="primary" id="meet-pet">함께 시작하기</button></div>`,'A NEW FRIEND');
  $('meet-pet').onclick=closeModal;
}
function confirmNewEgg(){
  if(busy||(game.s.hatched&&!game.ready()))return;
  modal(`<h2 class="modal-title">${game.s.hatched?esc(game.species.name)+'를 놓아줄까요?':'새로운 알을 만날까요?'}</h2><p class="modal-copy">현재 포켓몬, 레벨, 기술, 포인트, 날짜와 피로도를 모두 초기화하고 새 알을 받습니다. 기존 성장을 보관하려면 먼저 백업을 내려받으세요.</p><div class="modal-actions">${game.s.hatched?'<button class="secondary" id="backup-before-reset">현재 저장 백업</button>':''}<button class="primary" id="confirm-new-egg">놓아주고 새 알 받기</button><button class="secondary" id="cancel-new-egg">취소</button></div>`,'NEW BEGINNING');
  if($('backup-before-reset'))$('backup-before-reset').onclick=exportSave;
  $('cancel-new-egg').onclick=closeModal;
  $('confirm-new-egg').onclick=()=>{if(game.s.hatched)game.release();else game=new Game(db);save();closeModal();$('hatch-hint').textContent='알을 클릭해서 친구를 만나보세요';render();};
}
async function init(){try{const response=await fetch('data/pokedex.json?v=growth-1');if(!response.ok)throw Error('도감 데이터를 불러오지 못했어요.');db=await response.json();let state=null;try{const raw=localStorage.getItem(KEY);if(raw){state=JSON.parse(raw);if(state.schemaVersion===1){try{localStorage.setItem(KEY+'-legacy-backup',raw);}catch{}state=migrateState(db,state);}validateState(db,{...state,battle:null,pending:[],progressing:false});if(state.pending.some(e=>!['move','evolution'].includes(e.kind)||(e.kind==='move'&&!db.moves[e.moveId])||(e.kind==='evolution'&&!db.pokemon[e.to])))throw Error('성장 정보 오류');if(state.battle){for(const f of [state.battle.player,state.battle.enemy]){if(!db.pokemon[f.speciesId]||!Array.isArray(f.moves)||!f.moves.every(m=>db.moves[m.id]&&Number.isFinite(m.pp))||!Number.isFinite(f.hp)||!f.stages)throw Error('전투 정보 오류');}}}}catch{state=null;saveWarning='기존 저장을 읽을 수 없어 새로 시작했어요. 보관한 백업은 게임 안내에서 불러올 수 있어요.';}
    game=new Game(db,state??freshState(db));$('battle').onclick=startBattle;$('feed').onclick=()=>care('feed');$('sleep').onclick=()=>care('sleep');$('flee').onclick=()=>{if(busy)return;game.flee();save();render();say('쉼터로 돌아왔어요. 피로도는 그대로 유지돼요.');};$('help').onclick=showHelp;$('sources').onclick=showSources;$('dex-button').onclick=()=>showDex();$('learnset').onclick=()=>showLearnset();$('export-save').onclick=exportSave;
    render();if(!game.s.hatched){$('hatch-egg').onclick=hatchEgg;save();return;}save();if(game.s.battle)say('진행 중이던 전투를 이어서 시작해요. 기술을 선택하세요.');else say(saveWarning||`${game.species.name}가 주인님을 기다리고 있어요. 오늘은 함께 무엇을 할까요?`);if(game.s.pending.length||game.s.progressing)pump();
  }catch(e){say(e.message+' 새로고침해서 다시 시도해 주세요.');$('actions').innerHTML='<p class="error-view">게임 데이터를 불러오지 못했습니다. <button onclick="location.reload()">다시 시도</button></p>';}}
init();
