import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {Game,makePet,ITEMS,validateState,shopCatalog} from '../engine.js';
import {assignAbility,abilityOf,abilityItemTarget,HIDDEN_CHANCE,DROP_CHANCE,enter,endAbilities,abilityNotes} from '../abilities.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
const ab=(slug)=>Object.values(db.abilities).find(a=>a.slug===slug).id;
function setup(a=4,d=129){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,a,40);const p=g.fighter(g.pet),e=g.fighter(makePet(db,d,40));p.hp=p.maxHp=1000;e.hp=e.maxHp=1000;e.moves=[{id:150,pp:40}];g.s.battle={player:p,enemy:e,originalEnemy:makePet(db,d,40),turn:1,activeId:g.s.active};return {g,p,e};}
function hit(slug=null,target=null,move=52,{hp=1000}={}){const {g,p,e}=setup();if(slug)p.copiedAbilityId=ab(slug);if(target)e.copiedAbilityId=ab(target);p.moves=[{id:move,pp:30}];e.hp=hp;g.execute(p,e,move,[],()=>.5);return {g,p,e,damage:hp-e.hp};}
test('snapshot covers all species with Korean names, Gen7 regular and current hidden slots',()=>{assert.equal(Object.keys(db.abilities).length,121);for(const sp of Object.values(db.pokemon)){assert.ok(sp.abilities.some(a=>!a.hidden));for(const a of sp.abilities){assert.ok(db.abilities[a.id]?.name);assert.ok(db.abilities[a.id]?.description);}}assert.deepEqual(db.pokemon[94].abilities.map(a=>db.abilities[a.id].slug),['cursed-body']);assert.equal(db.pokemon[109].abilities.find(a=>!a.hidden).id,26);assert.ok(!db.pokemon[109].abilities.some(a=>a.id===256));assert.equal(db.pokemon[109].abilities.find(a=>a.hidden).id,1);});
test('hidden probability is exactly 3%, standard slots share 97%; no hidden slot never becomes hidden',()=>{assert.equal(HIDDEN_CHANCE,.03);let hidden=0;const counts={};for(let i=0;i<10000;i++){const p=assignAbility(db,makePet(db,16),()=>(i+.5)/10000);const a=abilityOf(db,p);if(a.hidden)hidden++;counts[p.abilitySlot]=(counts[p.abilitySlot]??0)+1;}assert.equal(hidden,300);assert.deepEqual(counts,{1:4850,2:4850,3:300});for(const r of [0,.029999,.03,.999]){const p=assignAbility(db,makePet(db,11),()=>r);assert.equal(abilityOf(db,p).hidden,false);}assert.equal(abilityOf(db,assignAbility(db,makePet(db,1),()=>.03)).hidden,false);});
test('hatch and all trainer/wild opponents roll hidden independently of shiny; save never rerolls',()=>{for(const hidden of [0,.03])for(const shiny of [0,.04]){const g=new Game(db);g.hatch(()=>0,()=>shiny,()=>hidden);assert.equal(abilityOf(db,g.pet).hidden,hidden===0);assert.equal(g.pet.shiny,shiny===0);g.s.pets[g.s.active].level=20;g.pet.hp=30;g.s.battleCount=10;const b=g.startBattle(()=>.5,()=>shiny,()=>0,()=>0,()=>hidden);assert.equal(b.enemyTeam.length,3);for(const p of b.enemyTeam){assert.equal(abilityOf(db,p).hidden,hidden===0);assert.equal(p.shiny,shiny===0);}const saved=JSON.stringify(g.s);assert.equal(JSON.stringify(new Game(db,JSON.parse(saved)).s),saved);}});
test('old saves get abilities once, including active battle and bench; no HP/moves/progress loss',()=>{const {g,p,e}=setup();delete g.pet.abilitySlot;delete p.abilitySlot;delete e.abilitySlot;delete g.s.battle.originalEnemy.abilitySlot;const hp=g.pet.hp,moves=[...g.pet.moves];const restored=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.ok(restored.pet.abilitySlot);assert.equal(restored.s.battle.player.abilitySlot,restored.pet.abilitySlot);assert.equal(restored.s.battle.enemy.abilitySlot,restored.s.battle.originalEnemy.abilitySlot);assert.equal(restored.pet.hp,hp);assert.deepEqual(restored.pet.moves,moves);const raw=JSON.stringify(restored.s);assert.equal(JSON.stringify(new Game(db,JSON.parse(raw)).s),raw);});
test('capsule switches standard slots; patch switches hidden and first standard; invalid uses are atomic',()=>{const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,16);g.s.coins=10000;g.buy('ability-capsule',2);g.buy('ability-patch',2);g.changeAbility('ability-capsule');assert.equal(g.pet.abilitySlot,2);g.changeAbility('ability-patch');assert.equal(g.pet.abilitySlot,3);const before=JSON.stringify(g.s);assert.throws(()=>g.changeAbility('ability-capsule'));assert.equal(JSON.stringify(g.s),before);g.changeAbility('ability-patch');assert.equal(g.pet.abilitySlot,1);g.s.pets[g.s.active]=makePet(db,11);assert.equal(abilityItemTarget(db,g.pet,'ability-patch'),null);assert.equal(abilityItemTarget(db,g.pet,'ability-capsule'),null);});
test('hidden slot follows evolution through a cocoon with no hidden ability',()=>{const g=new Game(db);g.hatch(()=>0,()=>1,()=>0);g.s.pets[g.s.active]=assignAbility(db,makePet(db,10),()=>0);g.evolveTo(11);assert.equal(g.pet.abilitySlot,3);assert.equal(abilityOf(db,g.pet).slug,'shed-skin');assert.equal(abilityOf(db,g.pet).hidden,false);g.evolveTo(12);assert.equal(abilityOf(db,g.pet).slug,'tinted-lens');assert.equal(abilityOf(db,g.pet).hidden,true);validateState(db,g.s);});
test('caught Imposter retains original hidden slot and transform move, not copied ability',()=>{const {g,p,e}=setup(4,132);const original=assignAbility(db,makePet(db,132,40),()=>0);g.s.battle.originalEnemy=original;g.s.battle.enemy=g.fighter(original);enter(g,g.s.battle.enemy,p,[]);assert.equal(g.s.battle.enemy.transformed,true);const out=g.battleItem('poke-ball',()=>0);const caught=g.s.pets[out.caughtId];assert.equal(abilityOf(db,caught).slug,'imposter');assert.deepEqual(caught.moves,[144]);assert.equal(caught.copiedAbilityId,undefined);});
test('victory drop threshold is 1%, supports all shop items and full stacks',()=>{assert.equal(DROP_CHANCE,.01);const {g}=setup();g.s.battle=null;const n=Object.keys(shopCatalog(db)).length;for(const r of [.01,.999])assert.equal(g.rollDrop([],()=>r),null);for(let i=0;i<n;i++){let calls=0;const id=g.rollDrop([],()=>calls++===0?.009999:(i+.5)/n);assert.ok(shopCatalog(db)[id]);}for(const id of Object.keys(shopCatalog(db)))g.s.inventory[id]=999;assert.equal(g.rollDrop([],()=>0),null);assert.ok(Object.values(g.s.inventory).every(n=>n===999));});
test('drop occurs once only on final victory, not loss draw capture or intermediate trainer KO',()=>{for(const outcome of ['win','lose','draw','intermediate']){const {g,p,e}=setup();let drops=0;g.rollDrop=()=>drops++;if(outcome==='win')e.hp=0;if(outcome==='lose')p.hp=0;if(outcome==='draw')g.s.battle.turn=60;if(outcome==='intermediate'){e.hp=0;Object.assign(g.s.battle,{kind:'trainer',enemyIndex:0,earnedXP:0,enemyTeam:[makePet(db,129),makePet(db,129),makePet(db,129)]});}g.endTurn([],[],()=>.5,()=>0);assert.equal(drops,outcome==='win'?1:0);}const {g}=setup();let drops=0;g.rollDrop=()=>drops++;g.battleItem('poke-ball',()=>0);assert.equal(drops,0);});
test('absorptions levitate and Mold Breaker alter actual damage',()=>{assert.equal(hit(null,'water-absorb',55).damage,0);assert.equal(hit(null,'volt-absorb',84).damage,0);assert.equal(hit(null,'levitate',89).damage,0);assert.ok(hit('mold-breaker','levitate',89).damage>0);assert.equal(hit(null,'flash-fire',52).damage,0);assert.equal(hit(null,'lightning-rod',84).e.stages['special-attack'],1);});
test('Technician Adaptability Thick Fat Multiscale and Tinted Lens alter damage',()=>{assert.ok(hit('technician').damage>hit().damage);assert.ok(hit('adaptability').damage>hit().damage);assert.ok(hit(null,'thick-fat').damage<hit().damage);assert.ok(hit(null,'multiscale').damage<hit().damage);assert.ok(hit('tinted-lens').damage>hit().damage);});
test('Sturdy prevents one hit KO, Skill Link breaks it with further hits',()=>{const {g,p,e}=setup();e.copiedAbilityId=ab('sturdy');p.copiedAbilityId=ab('skill-link');p.level=100;p.moves=[{id:31,pp:20},{id:82,pp:20}];e.hp=e.maxHp=20;g.execute(p,e,82,[],()=>.5);assert.equal(e.hp,1);e.hp=20;g.execute(p,e,31,[],()=>.5);assert.equal(e.hp,0);});
test('status immunities and Magic Guard work without persisting status outside battle',()=>{const {g,p,e}=setup();e.copiedAbilityId=ab('immunity');p.moves=[{id:77,pp:20}];g.execute(p,e,77,[],()=>.1);assert.equal(e.status,null);e.copiedAbilityId=ab('magic-guard');e.status='poison';const hp=e.hp;g.endTurn([],[],()=>.5);assert.equal(e.hp,hp);g.flee();assert.equal(g.pet.status,undefined);});
test('Intimidate triggers Defiant while Clear Body blocks the drop; entry is not replayed on load',()=>{const {g,p,e}=setup();p.copiedAbilityId=ab('intimidate');e.copiedAbilityId=ab('defiant');enter(g,p,e,[]);assert.equal(e.stages.attack,1);e.stages.attack=0;e.copiedAbilityId=ab('clear-body');enter(g,p,e,[]);assert.equal(e.stages.attack,0);const restored=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.equal(restored.s.battle.enemy.stages.attack,0);});
test('Speed Boost and Shed Skin activate at turn end; Drought and Cloud Nine control weather',()=>{const {g,p,e}=setup();p.copiedAbilityId=ab('drought');enter(g,p,e,[]);assert.equal(g.s.battle.weather,'sun');p.copiedAbilityId=ab('chlorophyll');const boosted=g.effectiveStat(p,'speed');e.copiedAbilityId=ab('cloud-nine');assert.equal(g.effectiveStat(p,'speed')*2,boosted);p.copiedAbilityId=ab('speed-boost');p.enteredTurn=0;endAbilities(g,p,e,[],()=>.5);assert.equal(p.stages.speed,1);p.copiedAbilityId=ab('shed-skin');p.status='poison';endAbilities(g,p,e,[],()=>0);assert.equal(p.status,null);});
test('Truant alternates turns and Pressure consumes two PP',()=>{const {g,p,e}=setup();p.copiedAbilityId=ab('truant');e.copiedAbilityId=ab('pressure');p.moves=[{id:52,pp:10}];g.execute(p,e,52,[],()=>.5);assert.equal(p.moves[0].pp,8);const hp=e.hp;g.execute(p,e,52,[],()=>.5);assert.equal(e.hp,hp);assert.equal(p.moves[0].pp,8);g.execute(p,e,52,[],()=>.5);assert.equal(p.moves[0].pp,6);});
test('hidden and shiny stars are independently visible and have accessible labels',()=>{const src=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');const context=vm.createContext({db,abilityOf});vm.runInContext(src.slice(src.indexOf('const shinyMark='),src.indexOf('const abilityLabel=')),context);context.p=assignAbility(db,makePet(db,1),()=>0);context.p.shiny=true;const html=vm.runInContext('shinyMark(p)',context);assert.match(html,/hidden-mark/);assert.match(html,/shiny-mark/);assert.match(html,/aria-label="숨겨진 특성"/);});
test('all UI element IDs exist and all new module dependencies are bundled',()=>{const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');const src=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');for(const id of ['pet-ability','ability-odds','hatch-odds'])assert.ok(html.includes(`id="${id}"`));assert.ok(src.includes('game.changeAbility(id)'));assert.ok(src.includes("['ability','특성']"));for(const file of ['abilities.js','engine.js','app.js'])assert.ok(fs.existsSync(new URL('../'+file,import.meta.url)));});
test('Magic Bounce reflects status without consuming defender PP and without reflection loop',()=>{const {g,p,e}=setup();e.copiedAbilityId=ab('magic-bounce');p.copiedAbilityId=ab('magic-bounce');p.moves=[{id:77,pp:10}];e.moves=[{id:77,pp:10}];g.execute(p,e,77,[],()=>.1);assert.equal(p.status,'poison');assert.equal(e.status,null);assert.equal(p.moves[0].pp,9);assert.equal(e.moves[0].pp,10);});
test('Regenerator restores HP on switching and Natural Cure clears battle status on exit',()=>{for(const [species,slug] of [[114,'regenerator'],[113,'natural-cure']]){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,species,40);g.pet.abilitySlot=db.pokemon[species].abilities.find(a=>db.abilities[a.id].slug===slug).slot;g.s.pets[501]=makePet(db,4,40);g.startBattle(()=>.5,()=>1,()=>1,()=>0,()=>.5);g.s.battle.enemy.moves=[{id:150,pp:40}];const f=g.s.battle.player;f.hp=1;f.status='poison';const old=g.s.active;g.battleSwitch(501,()=>.5);if(slug==='regenerator')assert.equal(g.s.pets[old].hp,1+Math.floor(f.maxHp/3));else assert.equal(g.s.battle.bench[old].status,null);}});
