import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,validateState,MAX_BOX} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function setup(){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets={1:makePet(db,1),2:makePet(db,4),3:makePet(db,7)};g.s.active=1;return g;}
test('deposit withdraw preserves full identity, HP, shiny, abilities, moves and held item',()=>{const g=setup();Object.assign(g.pet,{hp:1,shiny:true,heldItem:'quick-claw',abilitySlot:3});const before=structuredClone(g.pet);g.deposit(1);assert.equal(g.s.active,2);assert.deepEqual(g.s.box[1],before);g.withdraw(1);assert.deepEqual(g.s.pets[1],before);assert.equal(Object.keys(g.s.box).length,0);validateState(db,g.s);});
test('full-party swap is atomic and works with a full box',()=>{const g=setup();for(let i=0;i<MAX_BOX;i++)g.s.box[1000+i]=makePet(db,25);const old=g.pet,next=g.s.box[1000];g.withdraw(1000,1);assert.equal(g.pet,next);assert.equal(g.s.box[1],old);assert.equal(Object.keys(g.s.pets).length,3);assert.equal(Object.keys(g.s.box).length,MAX_BOX);const before=JSON.stringify(g.s);assert.throws(()=>g.withdraw(1001));assert.throws(()=>g.withdraw(1001,999));assert.throws(()=>g.deposit(2));assert.equal(JSON.stringify(g.s),before);});
test('last companion cannot be deposited; releasing it promotes a boxed pet without DAY reset',()=>{const g=setup();g.deposit(2);g.deposit(3);g.s.day=9;assert.throws(()=>g.deposit(1));g.release();assert.equal(g.s.day,9);assert.equal(g.s.hatched,true);assert.equal(g.s.active,2);assert.equal(Object.keys(g.s.box).length,1);});
test('full-party capture sends to box with collision-free ID and normal capture data',()=>{const g=setup();g.s.box[1000]=makePet(db,4);g.startBattle(()=>.5,()=>0,()=>1,()=>.5,()=>0);const enemy=structuredClone(g.s.battle.originalEnemy);g.s.battle.enemy.hp=1;const out=g.battleItem('poke-ball',()=>0);assert.equal(out.sentToBox,true);assert.equal(out.caughtId,1001);assert.equal(Object.keys(g.s.pets).length,3);assert.equal(g.s.box[1001].speciesId,enemy.speciesId);assert.equal(g.s.box[1001].hp,1);assert.equal(g.s.box[1001].shiny,true);assert.equal(g.s.box[1001].abilitySlot,enemy.abilitySlot);assert.equal(g.s.inventory['poke-ball'],4);validateState(db,g.s);});
test('legacy saves and populated box backup roundtrip; reject collisions and malformed box pets',()=>{const g=setup();delete g.s.box;const migrated=new Game(db,validateState(db,structuredClone(g.s)));assert.deepEqual(migrated.s.box,{});migrated.deposit(2);const copy=new Game(db,validateState(db,structuredClone(migrated.s)));assert.deepEqual(copy.s,migrated.s);const bad=structuredClone(copy.s);bad.box[1]=bad.pets[1];assert.throws(()=>validateState(db,bad));const badHP=structuredClone(copy.s);badHP.box[2].hp=-1;assert.throws(()=>validateState(db,badHP));});
test('box changes blocked in battle and growth; boxed healthy pets do not prevent party defeat',()=>{const g=setup();g.deposit(2);g.deposit(3);g.startBattle(()=>.5,()=>1,()=>1);let before=JSON.stringify(g.s);assert.throws(()=>g.deposit(1));assert.throws(()=>g.withdraw(2));assert.equal(JSON.stringify(g.s),before);g.s.battle.player.hp=0;assert.equal(g.endTurn([],[],()=>.5,()=>1).result,'lose');g.s.pending=[{kind:'move'}];before=JSON.stringify(g.s);assert.throws(()=>g.withdraw(2));assert.equal(JSON.stringify(g.s),before);});
