import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,validateState,SHINY_CHANCE,captureChance,shopCatalog} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function game(){const g=new Game(db);g.hatch(()=>.1,()=>1);return g;}
function battle(id=129){const g=game();const pet=makePet(db,id,7);g.s.battle={player:g.fighter(g.pet),enemy:g.fighter(pet),originalEnemy:pet,activeId:g.s.active,turn:1};return g;}
test('all species have capture rates and complete shiny images',()=>{for(const p of Object.values(db.pokemon)){assert.ok(Number.isInteger(p.captureRate)&&p.captureRate>0&&p.captureRate<=255);for(const suffix of ['', '-back'])assert.ok(fs.existsSync(new URL(`../assets/sprites/shiny/${p.id}${suffix}.png`,import.meta.url)));}});
test('shiny rate is exactly 4 percent, preserved through evolution and save',()=>{assert.equal(SHINY_CHANCE,.04);const g=new Game(db);g.hatch(()=>0,()=>SHINY_CHANCE/2);assert.equal(g.pet.shiny,true);g.s.coins=300;g.buy('evo-'+g.species.evolutions[0].itemId);g.stone();assert.equal(g.pet.shiny,true);const copy=new Game(db,validateState(db,JSON.parse(JSON.stringify(g.s))));assert.equal(copy.pet.shiny,true);const plain=new Game(db);plain.hatch(()=>0,()=>SHINY_CHANCE);assert.equal(plain.pet.shiny,false);});
test('old schema 2 save migrates without losing level moves HP money or progress',()=>{const old=game().s;old.schemaVersion=2;delete old.inventory;delete old.pets[old.active].shiny;delete old.pets[old.active].heldItem;delete old.pets[old.active].originSpeciesId;old.day=20;old.coins=431;old.pets[old.active].hp=10;const original=JSON.stringify(old);const g=new Game(db,old);assert.equal(g.s.day,20);assert.equal(g.s.coins,431);assert.equal(g.pet.hp,10);assert.equal(g.s.inventory['poke-ball'],5);assert.equal(g.pet.shiny,false);assert.equal(JSON.stringify(old),original);validateState(db,g.s);});
test('HGSS capture calculation and relative boost, HP status and ball modifiers',()=>{const g=battle(147),f=g.s.battle.enemy;const base=captureChance(db,f,'poke-ball',false);assert.ok(base>0&&base<.1);assert.equal(captureChance(db,f),Math.min(1,base*1.1));const normal=captureChance(db,f);f.hp=1;assert.ok(captureChance(db,f)>normal);const low=captureChance(db,f);f.status='sleep';assert.ok(captureChance(db,f)>low);assert.ok(captureChance(db,f,'ultra-ball')>=captureChance(db,f,'great-ball'));f.hp=0;assert.equal(captureChance(db,f),0);});
test('successful capture consumes one ball, persists original moves and shiny, and clears status',()=>{const g=battle(132);g.s.battle.enemy.shiny=true;g.s.battle.enemy.status='sleep';g.s.battle.enemy.transformed=true;g.s.battle.enemy.moves=[{id:52,pp:5}];const before=g.s.inventory['poke-ball'];const out=g.battleItem('poke-ball',()=>0);assert.equal(out.result,'caught');assert.equal(Object.keys(g.s.pets).length,2);assert.equal(g.s.inventory['poke-ball'],before-1);const caught=g.s.pets[out.caughtId];assert.equal(caught.shiny,true);assert.deepEqual(caught.moves,[144]);assert.equal(caught.status,undefined);assert.equal(g.s.battle,null);validateState(db,g.s);});
test('failed capture takes enemy turn; full party cannot consume a ball or advance turn',()=>{const g=battle();g.battleItem('poke-ball',()=>.99999);assert.equal(g.s.battle.turn,2);assert.equal(g.s.inventory['poke-ball'],4);g.s.pets[501]=makePet(db,4);g.s.pets[502]=makePet(db,4);const before=JSON.stringify(g.s);assert.throws(()=>g.battleItem('poke-ball'));assert.equal(JSON.stringify(g.s),before);});
test('potion restores 20 HP before enemy action, consumes turn and does not clear statuses',()=>{const g=battle();g.s.battle.player.hp=1;const before=g.s.inventory.potion;g.battleItem('potion',()=>.5);assert.equal(g.pet.hp,Math.min(g.s.battle.player.maxHp,21));assert.equal(g.s.battle.turn,2);assert.equal(g.s.inventory.potion,before-1);g.s.battle.player.hp=g.s.battle.player.maxHp;const state=JSON.stringify(g.s);assert.throws(()=>g.battleItem('potion'));assert.equal(JSON.stringify(g.s),state);});
test('shop prevents negative/infinite purchases and equipment is conserved',()=>{const g=game();g.s.coins=1000;g.buy('quick-claw');assert.equal(g.s.coins,400);g.equip('quick-claw');assert.equal(g.pet.heldItem,'quick-claw');assert.equal(g.s.inventory['quick-claw'],0);g.equip(null);assert.equal(g.s.inventory['quick-claw'],1);for(const n of [-1,0,Infinity,NaN,1.5])assert.throws(()=>g.buy('potion',n));const state=JSON.stringify(g.s);assert.throws(()=>g.buy('leftovers'));assert.equal(JSON.stringify(g.s),state);});
test('held items recover only living Pokemon and berries are consumed exactly once',()=>{const g=battle(),p=g.s.battle.player;p.heldItem='oran-berry';p.hp=1;g.endTurn([],[]);assert.equal(p.hp,11);assert.equal(g.pet.heldItem,null);g.endTurn([],[]);assert.equal(p.hp,11);p.heldItem='leftovers';g.endTurn([],[]);assert.equal(p.hp,11+Math.max(1,Math.floor(p.maxHp/16)));p.hp=0;g.endTurn([],[]);assert.equal(g.pet.hp,0);});
test('Quick Claw overrides speed only within a priority bracket',()=>{const g=battle();const p=g.s.battle.player,e=g.s.battle.enemy;p.heldItem='quick-claw';p.copiedStats={speed:1};e.copiedStats={speed:500};p.moves=[{id:33,pp:10}];e.moves=[{id:33,pp:10}];const ordered=[];g.attack=(a,d,id,who)=>ordered.push(who);g.endTurn=(logs,events)=>({logs,events});let out=g.act(33,()=>0);assert.equal(ordered[0],'player');assert.ok(out.logs.includes('선제공격손톱 발동!'));ordered.length=0;e.moves=[{id:98,pp:10}];g.act(33,()=>0);assert.equal(ordered[0],'enemy');});
test('party switch saves old HP/PP/status, and battle exit clears battle-only conditions',()=>{const g=battle();const first=g.s.active;g.s.pets[501]=makePet(db,4,7);g.s.battle.player.status='poison';g.s.battle.player.hp=10;g.s.battle.player.moves[0].pp=1;g.battleSwitch(501,()=>.5);assert.equal(g.s.active,501);assert.equal(g.s.pets[first].hp,10);g.battleSwitch(first,()=>.5);assert.equal(g.s.battle.player.status,'poison');assert.equal(g.s.battle.player.moves[0].pp,1);g.flee();g.s.fatigue=0;g.pet.hunger=100;g.startBattle(()=>.5,()=>1);assert.equal(g.s.battle.player.status,null);assert.ok(g.s.battle.player.moves[0].pp>1);});
test('release removes only chosen partner and returns held item; duplicates remain independent',()=>{const g=game(),first=g.s.active;g.s.pets[501]=makePet(db,g.pet.speciesId);g.pet.heldItem='quick-claw';g.s.coins=451;g.release();assert.equal(g.s.active,501);assert.equal(g.s.pets[first],undefined);assert.equal(g.s.coins,451);assert.equal(g.s.inventory['quick-claw'],1);validateState(db,g.s);});
test('damage events distinguish weakness resistance immunity and fixed damage',()=>{for(const [move,defender,effect] of [[52,1,2],[52,7,.5],[33,92,0],[69,74,1]]){const g=battle(defender),p=g.s.battle.player,e=g.s.battle.enemy;p.moves=[{id:move,pp:10}];const events=[];g.attack(p,e,move,'player',[],events,()=>.5);assert.equal(events[0].effect,effect);assert.equal(events[0].immune,effect===0);}});
test('all evolution items are sold and consumption is atomic if any requirement is missing',()=>{const catalog=shopCatalog(db);const g=game();g.s.pets[g.s.active]=makePet(db,125,30);g.s.inventory['trade-pass']=1;const before=JSON.stringify(g.s);assert.throws(()=>g.trade(466));assert.equal(JSON.stringify(g.s),before);assert.ok(catalog['evo-299']);g.s.coins=300;g.buy('evo-299');g.pet.heldItem='quick-claw';g.trade(466);assert.equal(g.s.inventory['evo-299'],0);assert.equal(g.s.inventory['trade-pass'],0);assert.equal(g.pet.heldItem,'quick-claw');});
