import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,validateState,EXPEDITIONS} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function ready(){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets={1:makePet(db,1,40)};g.s.active=1;g.s.expeditionFragments=3;return g;}
function reward(){const g=ready();g.s.specialShopOpen=true;g.s.legendRewardChoice='pending';return g;}
test('reward choice is mutually exclusive, persists, and cannot be claimed twice',()=>{const g=reward(),before=JSON.stringify(g.s);assert.throws(()=>g.chooseLegendReward('both'));assert.equal(JSON.stringify(g.s),before);assert.throws(()=>g.teachEgg(g.eggStock().bonus[0],0));g.chooseLegendReward('fragment');assert.equal(g.s.expeditionFragments,4);assert.equal(g.s.specialShopOpen,false);assert.throws(()=>g.chooseLegendReward('move'));const h=reward();h.chooseLegendReward('move');assert.equal(h.s.expeditionFragments,3);assert.equal(h.s.specialShopOpen,true);assert.throws(()=>h.chooseLegendReward('fragment'));assert.equal(new Game(db,structuredClone(h.s)).s.legendRewardChoice,'move');});
test('50 distinct species gives exactly one map and one of two mythical expeditions',()=>{const g=ready();g.s.caughtSpecies=db.enemyIds.slice(0,49);assert.throws(()=>g.claimAncientMap());g.recordCaught(db.enemyIds[49]);g.recordCaught(db.enemyIds[49]);assert.equal(g.s.caughtSpecies.length,50);g.claimAncientMap();assert.throws(()=>g.claimAncientMap());g.unlockExpedition(151,()=>1,()=>.5);assert.equal(g.s.mythicalChoice,151);assert.equal(g.s.expeditionFragments,3);assert.throws(()=>g.unlockExpedition(251));validateState(db,g.s);});
test('unlock consumes three fragments once, enforces level, freezes shiny and ability across retries',()=>{let g=ready();g.pet.level=39;assert.throws(()=>g.unlockExpedition(144));g.pet.level=40;g.unlockExpedition(144,()=>0,()=>0);assert.equal(g.s.expeditionFragments,0);assert.equal(g.s.expeditions[144].pet.level,45);assert.equal(g.s.expeditions[144].pet.shiny,true);assert.throws(()=>g.unlockExpedition(144));const original=structuredClone(g.s.expeditions[144].pet);g.startExpedition(144);const b=structuredClone(g.s.battle);g=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.deepEqual(g.s.battle,b);g.flee();assert.throws(()=>g.startExpedition(144));g.sleep();g.startExpedition(144);assert.deepEqual(g.s.battle.originalEnemy,original);});
test('legend catch goes to box, records collection and permanently blocks duplicate catch even after release',()=>{let g=ready();g.s.pets[2]=makePet(db,4,40);g.s.pets[3]=makePet(db,7,40);g.unlockExpedition(145,()=>0,()=>.5);g.startExpedition(145);g.s.battle.enemy.hp=1;const out=g.battleItem('poke-ball',()=>0);assert.equal(out.sentToBox,true);assert.equal(g.s.box[out.caughtId].shiny,true);assert.ok(g.s.caughtSpecies.includes(145));assert.equal(g.s.expeditions[145].captured,true);g.withdraw(out.caughtId,1);g.release();assert.ok(g.s.caughtSpecies.includes(145));g.sleep();g.startExpedition(145);assert.equal(g.s.battle.rematch,true);const before=JSON.stringify(g.s);assert.throws(()=>g.battleItem('poke-ball',()=>0));assert.equal(JSON.stringify(g.s),before);});
test('defeat or KO does not close expedition; retry next day and no trainer progress',()=>{for(const lose of [true,false]){const g=ready();g.unlockExpedition(146);g.startExpedition(146);const battleCount=g.s.battleCount;g.s.battle[lose?'player':'enemy'].hp=0;const out=g.endTurn([],[],()=>.5,()=>1);assert.equal(out.result,lose?'lose':'win');g.s.pending=[];g.s.progressing=false;assert.equal(g.s.expeditions[146].captured,false);assert.equal(g.s.trainerCycle,0);assert.equal(g.s.battleCount,battleCount);g.sleep();assert.doesNotThrow(()=>g.startExpedition(146));}});
test('legacy migration records current party/box origins without awarding duplicate maps',()=>{const g=ready();g.s.box[10]=makePet(db,25,40);g.s.box[10].originSpeciesId=172;delete g.s.caughtSpecies;delete g.s.expeditions;delete g.s.expeditionFragments;delete g.s.ancientMapClaimed;delete g.s.mythicalChoice;delete g.s.legendRewardChoice;const h=new Game(db,structuredClone(g.s));assert.ok(h.s.caughtSpecies.includes(1)&&h.s.caughtSpecies.includes(25)&&h.s.caughtSpecies.includes(172));assert.equal(h.s.ancientMapClaimed,false);validateState(db,h.s);const bad=structuredClone(h.s);bad.expeditionFragments=-1;assert.throws(()=>validateState(db,bad));});
test('all 11 expedition species have data and four local sprites but are excluded from wild and eggs',()=>{assert.equal(EXPEDITIONS.length,11);for(const site of EXPEDITIONS){assert.ok(db.pokemon[site.id].learnset.length);assert.ok(!db.enemyIds.includes(site.id));assert.ok(!db.hatchTable.some(x=>x.id===site.id));for(const folder of ['sprites','shiny'])for(const suffix of ['','-back'])assert.equal(fs.readFileSync(new URL(`../assets/${folder}/${site.id}${suffix}.png`,import.meta.url)).subarray(1,4).toString(),'PNG');}});
test('evolution registers species and releasing the last companion preserves collection/map',()=>{const g=ready();g.evolveTo(2);assert.ok(g.s.caughtSpecies.includes(2));g.s.ancientMapClaimed=true;g.s.day=99;g.unlockExpedition(144);g.s.expeditions[144].lastAttemptDay=99;g.release();assert.equal(g.s.day,1);assert.equal(g.s.expeditions[144].lastAttemptDay,0);assert.ok(g.s.caughtSpecies.includes(2));assert.equal(g.s.ancientMapClaimed,true);});
test('unlock insufficient funds and full storage start are atomic; level caps at 100',()=>{const g=ready();g.s.expeditionFragments=2;let before=JSON.stringify(g.s);assert.throws(()=>g.unlockExpedition(150));assert.equal(JSON.stringify(g.s),before);g.s.expeditionFragments=3;g.s.pets[1]=makePet(db,1,100);g.unlockExpedition(150);assert.equal(g.s.expeditions[150].pet.level,100);g.s.pets[2]=makePet(db,4,40);g.s.pets[3]=makePet(db,7,40);for(let i=0;i<120;i++)g.s.box[1000+i]=makePet(db,1);before=JSON.stringify(g.s);assert.throws(()=>g.startExpedition(150));assert.equal(JSON.stringify(g.s),before);});
test('captured legendary rematch grants only points and cannot stack map rewards',()=>{const g=ready();g.unlockExpedition(243);g.s.expeditions[243].captured=true;g.startExpedition(243);g.s.battle.enemy.hp=0;const xp=g.pet.exp,coins=g.s.coins,bag=structuredClone(g.s.inventory);assert.equal(g.endTurn([],[],()=>.5,()=>0).result,'win');assert.equal(g.pet.exp,xp);assert.equal(g.s.coins,coins+300);assert.deepEqual(g.s.inventory,bag);assert.equal(g.s.specialShopOpen,false);});
