import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,battleExperience,validateState,ITEMS} from '../engine.js';
import {side,entryHazards,fieldDescriptions} from '../field.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
const mid=slug=>Object.values(db.moves).find(m=>m.slug===slug).id;
function battle(a=7,d=19){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,a,40);g.startBattle(()=>.5,()=>1,()=>1,()=>0,()=>.5);const b=g.s.battle;b.player=g.fighter(g.pet);b.enemy=g.fighter(makePet(db,d,35));b.player.copiedAbilityId=0;b.enemy.copiedAbilityId=0;return g;}
function move(g,slug,a=g.s.battle.player,d=g.s.battle.enemy,r=.5){const id=mid(slug);a.moves=[{id,pp:50}];const logs=[];g.execute(a,d,id,logs,()=>r);return logs;}
function ability(f,slug){f.copiedAbilityId=Number(Object.entries(db.abilities).find(([,a])=>a.slug===slug)?.[0]);assert.ok(f.copiedAbilityId);}
test('Spikes caps at three layers with correct Gen4 fractions and grounding',()=>{const g=battle(),b=g.s.battle,e=b.enemy;e.maxHp=e.hp=240;for(let n=1;n<=3;n++){move(g,'spikes');e.hp=240;entryHazards(g,e,[]);assert.equal(240-e.hp,[0,30,40,60][n]);}move(g,'spikes');assert.equal(side(g,e).spikes,3);e.typeIds=[3];e.hp=240;entryHazards(g,e,[]);assert.equal(e.hp,240);e.heldItem='iron-ball';entryHazards(g,e,[]);assert.equal(e.hp,180);e.hp=240;ability(e,'magic-guard');entryHazards(g,e,[]);assert.equal(e.hp,240);});
test('Stealth Rock applies Rock matchup; boots prevent damage and poison absorption',()=>{const g=battle(),e=g.s.battle.enemy;move(g,'stealth-rock');e.typeIds=[10,3];e.hp=e.maxHp=240;entryHazards(g,e,[]);assert.equal(e.hp,120);e.heldItem='heavy-duty-boots';entryHazards(g,e,[]);assert.equal(e.hp,120);side(g,e).toxicSpikes=2;e.typeIds=[4];entryHazards(g,e,[]);assert.equal(side(g,e).toxicSpikes,2);});
test('Toxic Spikes poison/two-layer toxic, Flying immunity, Poison absorption, Steel immunity',()=>{const g=battle(),e=g.s.battle.enemy;move(g,'toxic-spikes');entryHazards(g,e,[]);assert.equal(e.status,'poison');assert.equal(e.toxic,false);move(g,'toxic-spikes');e.status=null;entryHazards(g,e,[]);assert.equal(e.toxic,true);e.status=null;e.typeIds=[3];entryHazards(g,e,[]);assert.equal(e.status,null);e.typeIds=[9];entryHazards(g,e,[]);assert.equal(e.status,null);e.typeIds=[4];entryHazards(g,e,[]);assert.equal(side(g,e).toxicSpikes,0);});
test('Rapid Spin clears own hazards and seed only on hit; Ghost blocks it',()=>{const g=battle(),b=g.s.battle;Object.assign(side(g,b.player),{spikes:3,stealthRock:1,toxicSpikes:2});b.player.seeded=true;b.enemy.typeIds=[8];move(g,'rapid-spin');assert.equal(side(g,b.player).spikes,3);b.enemy.typeIds=[1];move(g,'rapid-spin');assert.equal(side(g,b.player).spikes,0);assert.equal(b.player.seeded,false);assert.equal(b.player.stages.speed,0);});
test('Defog removes target side only in Gen4, not own Spikes',()=>{const g=battle(),b=g.s.battle;side(g,b.player).spikes=2;Object.assign(side(g,b.enemy),{spikes:3,reflect:4,safeguard:5});move(g,'defog');assert.equal(side(g,b.player).spikes,2);assert.equal(side(g,b.enemy).spikes,0);assert.equal(side(g,b.enemy).reflect,0);assert.equal(b.enemy.stages.evasion,-1);});
test('Magic Bounce reflects hazard placement and Protect does not block hazards',()=>{const g=battle(),b=g.s.battle;b.enemy.guard=true;move(g,'spikes');assert.equal(side(g,b.enemy).spikes,1);ability(b.enemy,'magic-bounce');move(g,'spikes');assert.equal(side(g,b.player).spikes,1);assert.equal(side(g,b.enemy).spikes,1);});
test('Reflect halves physical damage; critical and Infiltrator bypass; Light Clay lasts eight turns',()=>{const g=battle(),b=g.s.battle,e=b.enemy;e.hp=e.maxHp=10000;const hit=r=>{e.hp=10000;move(g,'tackle',b.player,e,r);return 10000-e.hp;};const normal=hit(.5);side(g,e).reflect=5;assert.equal(hit(.5),Math.max(1,Math.floor(normal/2)));ability(b.player,'infiltrator');assert.equal(hit(.5),normal);b.player.copiedAbilityId=0;const crit=hit(0);side(g,e).reflect=0;assert.equal(hit(0),crit);b.player.heldItem='light-clay';move(g,'reflect');assert.equal(side(g,b.player).reflect,8);move(g,'brick-break',e,b.player);assert.equal(side(g,b.player).reflect,0);});
test('Safeguard blocks status moves, not entry poison; Toxic increases and cures reset',()=>{const g=battle(),b=g.s.battle;side(g,b.enemy).safeguard=5;move(g,'toxic');assert.equal(b.enemy.status,null);side(g,b.enemy).toxicSpikes=2;entryHazards(g,b.enemy,[]);assert.equal(b.enemy.status,'poison');b.enemy.hp=b.enemy.maxHp=160;b.player.hp=b.player.maxHp=1000;g.endTurn([],[],()=>.5,()=>1);assert.equal(b.enemy.hp,150);g.endTurn([],[],()=>.5,()=>1);assert.equal(b.enemy.hp,130);b.enemy.status=null;g.endTurn([],[],()=>.5,()=>1);assert.equal(b.enemy.toxic,false);});
test('Leech Seed Big Root recovery and Liquid Ooze; Grass immune and switch removes seed',()=>{const g=battle(),b=g.s.battle;b.player.heldItem='big-root';b.player.hp=50;b.player.maxHp=200;b.enemy.hp=b.enemy.maxHp=160;move(g,'leech-seed');g.endTurn([],[],()=>.5,()=>1);assert.equal(b.player.hp,76);assert.equal(b.enemy.hp,140);ability(b.enemy,'liquid-ooze');g.endTurn([],[],()=>.5,()=>1);assert.equal(b.player.hp,50);});
test('Grip Claw binds five turns and Shed Shell allows switch; incoming Spikes precede attack',()=>{const g=battle(),b=g.s.battle;b.enemy.heldItem='grip-claw';move(g,'bind',b.enemy,b.player);assert.equal(b.player.bound.turns,5);g.s.pets[900]=makePet(db,1,40);assert.throws(()=>g.battleSwitch(900),/교대/);b.player.heldItem='shed-shell';side(g,b.player).spikes=3;g.enemyMove=()=>mid('splash');const hp=g.s.pets[900].hp;g.battleSwitch(900,()=>.5);assert.equal(g.pet.hp,hp-Math.floor(hp/4));assert.equal(b.player.bound,null);});
test('trainer entry hazards can KO remaining team, award XP once and increment one trainer victory',()=>{const g=battle(),b=g.s.battle;b.kind='trainer';b.enemyIndex=0;b.enemyTeam=[makePet(db,19,35),makePet(db,4,30),makePet(db,7,30)];b.enemyTeam[1].hp=b.enemyTeam[2].hp=1;b.enemy.hp=0;side(g,b.enemy).spikes=3;const xp=b.enemyTeam.reduce((n,p)=>n+battleExperience(p.level),0),before=g.pet.exp;assert.equal(g.endTurn([],[],()=>.5,()=>1).result,'win');assert.equal(g.s.trainerWins,1);assert.equal(g.pet.exp,before+xp);});
test('forced trainer switch preserves remaining queue HP and PP',()=>{const g=battle(),b=g.s.battle;b.kind='trainer';b.enemyTeam=[makePet(db,19,35),makePet(db,4,30),makePet(db,7,30)];b.enemy.hp=12;b.enemy.moves[0].pp=1;const old=b.enemy;move(g,'roar');assert.notEqual(b.enemy,old);assert.equal(b.enemyBench[2],old);assert.equal(b.enemyBench[2].hp,12);b.enemy.hp=0;g.endTurn([],[],()=>.5,()=>1);assert.equal(b.enemyIndex,1);b.enemy.hp=0;g.endTurn([],[],()=>.5,()=>1);assert.equal(b.enemy,old);assert.equal(b.enemy.moves[0].pp,1);});
test('field state, toxic and timers survive reload; UI includes layers turns and volatile details',()=>{const g=battle(),b=g.s.battle;move(g,'spikes');move(g,'reflect');move(g,'gravity');b.player.seeded=true;b.enemy.toxic=true;b.enemy.status='poison';const copy=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.deepEqual(copy.s.battle,g.s.battle);const labels=fieldDescriptions(copy).map(x=>x.label).join(' ');assert.match(labels,/1층/);assert.match(labels,/5턴/);assert.match(labels,/씨뿌리기/);assert.match(labels,/맹독/);});
test('egg shop locks before five trainer wins, atomic payment, four slots and save compatibility',()=>{const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,1,20);g.s.coins=50000;assert.equal(g.eggStock().eggs.length,0);assert.throws(()=>g.teachEgg(73),/5번째/);g.s.trainerWins=5;g.s.specialShopOpen=true;const stock=g.eggStock(()=>.5);const id=stock.eggs.find(id=>!g.pet.moves.includes(id));assert.ok(id);g.pet.moves=[33,45,73,22];const saved=JSON.stringify(g.s);assert.throws(()=>g.teachEgg(id));assert.equal(JSON.stringify(g.s),saved);const price=g.eggPrice(id);g.teachEgg(id,0);assert.equal(g.pet.moves.length,4);assert.equal(g.pet.moves[0],id);assert.equal(g.s.coins,50000-price);const copy=new Game(db,validateState(db,JSON.parse(JSON.stringify(g.s))));assert.equal(copy.s.trainerWins,5);assert.deepEqual(copy.eggStock(()=>0),g.eggStock());});
test('six unique daily bonus offers persist and refresh only next day; Ditto receives the same unrestricted offers',()=>{const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,1,20);g.s.trainerWins=5;g.s.specialShopOpen=true;const before=g.eggStock(()=>.1);assert.equal(before.bonus.length,6);assert.equal(new Set(before.bonus).size,6);assert.deepEqual(g.eggStock(()=>.9),before);g.s.day++;assert.notDeepEqual(g.eggStock(()=>.9).bonus,before.bonus);g.pet.speciesId=132;const shared=g.eggStock();assert.equal(shared.bonus.length,6);g.pet.speciesId=1;assert.deepEqual(g.eggStock().bonus,shared.bonus);});
test('data sources and all sale moves exist; relevant actual TMs use compatible Gen4 species',()=>{for(const p of Object.values(db.pokemon)){for(const id of [...p.eggMoves,...p.bonusMoves])assert.ok(db.moves[id]);assert.ok(!p.bonusMoves.some(id=>p.eggMoves.includes(id)));for(const src of Object.values(p.eggMoveSources))assert.ok(src.generation>=2&&src.generation<=9);}assert.ok(db.pokemon[74].tmMoves.includes(446));assert.ok(!db.pokemon[132].tmMoves.includes(446));assert.equal(db.tms['tm-76'].generation,4);assert.equal(ITEMS['light-clay'].kind,'held');});
test('switching restores transformed moves and clears volatile state but keeps major poison',()=>{const g=battle(132),b=g.s.battle;move(g,'transform');assert.equal(b.player.transformed,true);b.player.status='poison';b.player.toxic=true;b.player.toxicCounter=6;b.player.seeded=true;b.player.recharge=true;g.s.pets[900]=makePet(db,1,40);g.enemyMove=()=>mid('splash');g.battleSwitch(900,()=>.5);const ditto=b.bench[Object.keys(g.s.pets).map(Number).find(id=>id!==900)];assert.equal(ditto.transformed,undefined);assert.equal(ditto.seeded,false);assert.equal(ditto.recharge,false);assert.equal(ditto.toxicCounter,0);assert.equal(ditto.status,'poison');});
test('Tailwind, Iron Ball and Trick Room modify effective speed and actual action order',()=>{const g=battle(25,19),b=g.s.battle;const base=g.effectiveStat(b.player,'speed');move(g,'tailwind');assert.equal(g.effectiveStat(b.player,'speed'),base*2);b.player.heldItem='iron-ball';assert.equal(g.effectiveStat(b.player,'speed'),base);move(g,'trick-room');b.player.moves=[{id:33,pp:30}];b.enemy.moves=[{id:33,pp:30}];b.player.hp=b.player.maxHp=b.enemy.hp=b.enemy.maxHp=10000;const slower=g.effectiveStat(b.player,'speed')<g.effectiveStat(b.enemy,'speed')?'player':'enemy';assert.equal(g.act(33,()=>.5).events[0].who,slower);});
test('field timers expire and fifth trainer win unlocks shop only after final opponent',()=>{const g=battle(),b=g.s.battle;g.s.trainerWins=4;b.kind='trainer';b.legend=true;b.enemyTeam=[makePet(db,19,35),makePet(db,19,35),makePet(db,19,35)];side(g,b.player).reflect=1;b.enemy.hp=0;g.endTurn([],[],()=>.5,()=>1);assert.equal(side(g,b.player).reflect,0);assert.equal(g.s.trainerWins,4);b.enemy.hp=0;g.endTurn([],[],()=>.5,()=>1);assert.equal(g.s.trainerWins,4);b.enemy.hp=0;const out=g.endTurn([],[],()=>.5,()=>1);assert.equal(g.s.trainerWins,5);assert.ok(out.logs.some(x=>x.includes('특별상점')));});
