import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,battleExperience,validateState,initialMoves} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function game(id,level=7,random=()=>.1){const g=new Game(db);g.s.hatched=true;g.s.active=id;g.s.pets[id]=makePet(db,id,level,random);return g;}
function settle(g){let n=0;while(g.s.pending.length||g.s.progressing){assert.ok(n++<500);const e=g.s.pending[0]??g.progress();if(!e)break;e.kind==='move'?g.chooseMove(0):g.chooseEvolution(true);}}
test('Pichu replaces only the egg candidate, friendship then thunder stone evolution works',()=>{assert.ok(db.starterIds.includes(172));assert.ok(!db.starterIds.includes(25));assert.ok(db.enemyIds.includes(25));const g=game(172);g.pet.friendship=214;g.awardXP(g.nextXp()-g.pet.exp);settle(g);assert.equal(g.pet.speciesId,172);g.awardXP(g.nextXp()-g.pet.exp);settle(g);assert.equal(g.pet.speciesId,25);g.s.coins=300;g.buy('evo-'+g.species.evolutions[0].itemId);g.stone();assert.equal(g.pet.speciesId,26);validateState(db,g.s);const old=game(25,42);old.pet.shiny=true;const restored=new Game(db,validateState(db,structuredClone(old.s)));assert.equal(restored.pet.speciesId,25);assert.equal(restored.pet.level,42);assert.equal(restored.pet.shiny,true);});
test('all 14 Hoenn chains grow to their final forms with four moves and save compatibility',()=>{assert.deepEqual(db.hoennStarterIds,[252,255,258,265,270,273,280,287,293,304,328,363,371,374]);const finals=[254,257,260,267,272,275,282,289,295,306,330,365,373,376];for(const [i,id] of db.hoennStarterIds.entries()){const g=game(id);assert.ok(db.starterIds.includes(id));assert.ok(initialMoves(db,id,7).length);g.awardXP(db.experience[g.species.growthRateId][60]-g.pet.exp);settle(g);if(g.species.evolutions.some(e=>e.trigger==='use-item')){g.s.coins=300;g.buy('evo-'+g.species.evolutions[0].itemId);g.stone();}assert.equal(g.pet.speciesId,finals[i]);assert.ok(g.pet.moves.length<=4);validateState(db,g.s);}});
test('Wurmple branch is fixed through backup and both branches reach their correct final evolution',()=>{for(const [r,branch,last] of [[.1,266,267],[.9,268,269]]){let g=game(265,7,()=>r);assert.equal(g.pet.evolutionBranch,branch);g=new Game(db,validateState(db,JSON.parse(JSON.stringify(g.s))));g.awardXP(g.nextXp()-g.pet.exp);settle(g);assert.equal(g.pet.speciesId,branch);g.awardXP(db.experience[g.species.growthRateId][10]-g.pet.exp);settle(g);assert.equal(g.pet.speciesId,last);assert.equal(g.pet.evolutionBranch,branch);}});
test('win XP is reduced 20 percent with floor rounding, currency and saved XP remain intact',()=>{for(const level of [7,12,30,50,100])assert.equal(battleExperience(level),Math.floor((40+3*level*level)*.8));const g=game(4,50),e=g.fighter(makePet(db,129,7));e.hp=0;g.s.battle={player:g.fighter(g.pet),enemy:e,turn:1,activeId:g.s.active};const before=g.pet.exp,money=g.s.coins;g.endTurn([],[]);assert.equal(g.pet.exp,before+149);assert.equal(g.s.coins,money+80);});
test('new dataset preserves HGSS types and sprites at the user deployed paths',()=>{assert.deepEqual(db.pokemon[280].typeIds,[14]);assert.equal(db.pokemon[172].evolutions[0].minFriendship,220);for(const p of Object.values(db.pokemon))for(const dir of ['sprites','shiny'])for(const suffix of ['','-back']){const data=fs.readFileSync(new URL(`../assets/${dir}/${p.id}${suffix}.png`,import.meta.url));assert.equal(data.subarray(1,4).toString(),'PNG');}const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.ok(app.includes("assets/${shiny?'shiny':'sprites'}"));});
