import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,ITEMS,medicineUsable,SHINY_CHANCE,validateState} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function setup(){const g=new Game(db);g.hatch(()=>0,()=>1);const p=g.fighter(makePet(db,4,50)),e=g.fighter(makePet(db,129,50));p.hp=p.maxHp=1000;e.hp=e.maxHp=1000;e.moves=[{id:150,pp:40}];g.s.battle={player:p,enemy:e,turn:1,activeId:g.s.active};return {g,p,e};}
function hit(item,id=52,target=129){const {g,p,e}=setup();p.heldItem=item;e.speciesId=target;p.moves=[{id,pp:20}];g.execute(p,e,id,[],()=>.5);return {damage:1000-e.hp,p,e};}
test('4 percent boundary applies independently to eggs and wild encounters',()=>{assert.equal(SHINY_CHANCE,.04);for(const [r,expected] of [[0,true],[.039999,true],[.04,false],[.999,false]]){const g=new Game(db);g.hatch(()=>0,()=>r);assert.equal(g.pet.shiny,expected);g.startBattle(()=>.5,()=>r);assert.equal(g.s.battle.enemy.shiny,expected);}});
test('type and class boosts work without boosting fixed damage or the wrong class',()=>{assert.ok(hit('charcoal').damage>hit(null).damage);assert.equal(hit('mystic-water').damage,hit(null).damage);assert.ok(hit('wise-glasses').damage>hit(null).damage);assert.equal(hit('muscle-band').damage,hit(null).damage);assert.ok(hit('muscle-band',33).damage>hit(null,33).damage);for(const item of ['life-orb','expert-belt','black-belt'])assert.equal(hit(item,69).damage,50);assert.equal(hit('expert-belt').damage,hit(null).damage);assert.ok(hit('expert-belt',52,1).damage>hit(null,52,1).damage);});
test('Life Orb recoil requires a successful hit and Shell Bell heals actual damage',()=>{assert.equal(hit('life-orb').p.hp,900);assert.equal(hit('life-orb',33,92).p.hp,1000);const {g,p,e}=setup();p.hp=500;p.heldItem='shell-bell';p.moves=[{id:52,pp:20}];e.hp=3;g.execute(p,e,52,[],()=>.5);assert.equal(p.hp,501);assert.equal(e.hp,0);});
test('Sitrus and status berries trigger once, Chesto only cures sleep',()=>{const {g,p}=setup();p.hp=500;p.heldItem='sitrus-berry';g.heldRecovery(p,[]);assert.equal(p.hp,750);assert.equal(p.heldItem,null);p.status='poison';p.confused=3;p.heldItem='lum-berry';g.heldRecovery(p,[]);assert.equal(p.status,null);assert.equal(p.confused,0);assert.equal(p.heldItem,null);p.heldItem='chesto-berry';p.status='burn';g.heldRecovery(p,[]);assert.equal(p.heldItem,'chesto-berry');p.status='sleep';g.heldRecovery(p,[]);assert.equal(p.status,null);assert.equal(p.heldItem,null);});
test('status medicine works at full HP, invalid medicine never consumes inventory or turn',()=>{const {g,p}=setup();p.status='burn';g.s.inventory['burn-heal']=2;assert.ok(medicineUsable(ITEMS['burn-heal'],p));g.battleItem('burn-heal',()=>.5);assert.equal(p.status,null);assert.equal(g.s.battle.turn,2);assert.equal(g.s.inventory['burn-heal'],1);const before=JSON.stringify(g.s);assert.throws(()=>g.battleItem('burn-heal'));assert.equal(JSON.stringify(g.s),before);p.hp=1;p.status='poison';p.confused=3;g.s.inventory['full-restore']=1;g.battleItem('full-restore',()=>.5);assert.equal(p.hp,1000);assert.equal(p.status,null);assert.equal(p.confused,0);});
test('Clear Amulet prevents opposing stat drops; Covert Cloak blocks secondaries but not status moves',()=>{for(const held of [null,'clear-amulet','covert-cloak']){const {g,p,e}=setup();e.heldItem=held;p.moves=[{id:45,pp:20}];g.execute(p,e,45,[],()=>0);assert.equal(e.stages.attack,held==='clear-amulet'?0:-1);}for(const held of [null,'covert-cloak']){const {g,p,e}=setup();e.heldItem=held;p.moves=[{id:52,pp:20},{id:86,pp:20}];g.execute(p,e,52,[],()=>0);assert.equal(e.status,held?null:'burn');e.status=null;g.execute(p,e,86,[],()=>0);assert.equal(e.status,'paralysis');}});
test('all new items can be bought and held items survive save restore',()=>{const g=new Game(db);g.hatch(()=>0,()=>1);g.s.coins=100000;for(const [id,item] of Object.entries(ITEMS)){g.buy(id);if(item.kind==='held'){g.equip(id);validateState(db,g.s);g.equip(null);}}assert.equal(Object.keys(ITEMS).length,45);assert.equal(Object.values(ITEMS).filter(i=>i.boostType).length,17);});
