import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,validateState,encounterPool} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
const johto=Array.from({length:100},(_,i)=>i+152).filter(id=>![243,244,245,249,250,251].includes(id));
test('all 94 ordinary Johto species have learnsets, abilities, stats and reachable encounters',()=>{assert.equal(johto.length,94);for(const id of johto){const p=db.pokemon[id];assert.ok(p?.learnset.length);assert.ok(p.abilities.length);assert.equal(Object.keys(p.stats).length,6);assert.ok(encounterPool(db,p.encounter.minLevel).includes(id));for(const m of p.learnset)assert.ok(db.moves[m.moveId]);const g=new Game(db);g.s.pets={1:makePet(db,id,40)};g.s.active=1;g.s.hatched=true;validateState(db,g.s);g.startBattle(()=>.5,()=>1,()=>1);assert.doesNotThrow(()=>g.act(g.usable(g.s.battle.player)[0]?.id??-1,()=>.5));}});
test('Johto exclusion and fixed starter policy',()=>{for(const id of [243,244,245,249,250,251]){assert.ok(db.pokemon[id]);assert.ok(!db.enemyIds.includes(id));}assert.equal(db.starterIds.length,42);for(const id of db.meta.johtoExpansion.newSpeciesIds){assert.ok(!db.starterIds.includes(id));assert.ok(!db.hatchTable.some(e=>e.id===id));}assert.equal(db.hatchTable.filter(e=>[132,133,147].includes(e.id)).reduce((n,e)=>n+e.weight,0)/db.hatchTable.reduce((n,e)=>n+e.weight,0),.06);});
test('Johto normal/shiny front/back images are valid PNGs',()=>{for(const id of johto)for(const folder of ['sprites','shiny'])for(const suffix of ['','-back']){const b=fs.readFileSync(new URL(`../assets/${folder}/${id}${suffix}.png`,import.meta.url));assert.equal(b.subarray(1,4).toString(),'PNG');}});
test('cross-generation evolutions and late Tyranitar gates exist',()=>{for(const [from,to] of [[42,169],[95,208],[123,212],[117,230],[113,242],[137,233]])assert.ok(db.pokemon[from].evolutions.some(e=>e.to===to));assert.ok(!encounterPool(db,54).includes(248));assert.ok(encounterPool(db,55).includes(248));});
test('every Johto species can be captured shiny into a full-party box and restored',()=>{for(const id of johto){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets={1:makePet(db,1,40),2:makePet(db,4,40),3:makePet(db,7,40)};g.s.active=1;const original=makePet(db,id,40);original.shiny=true;g.s.battle={kind:'wild',player:g.fighter(g.pet),enemy:g.fighter(original),originalEnemy:original,activeId:1,turn:1};g.s.battle.enemy.hp=1;const out=g.battleItem('poke-ball',()=>0);assert.equal(out.sentToBox,true);assert.equal(g.s.box[out.caughtId].speciesId,id);assert.equal(g.s.box[out.caughtId].shiny,true);const copy=new Game(db,validateState(db,JSON.parse(JSON.stringify(g.s))));copy.withdraw(out.caughtId,1);assert.equal(copy.pet.speciesId,id);assert.equal(copy.pet.shiny,true);assert.ok(copy.pet.moves.every(mid=>db.moves[mid]));}});
