import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,LEGEND_TRAINERS,validateState,battleExperience} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function ready(){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,1,30);g.s.battleCount=10;g.s.coins=50000;return g;}
function encounter(g,appearance=0){g.s.fatigue=0;g.pet.hp=100;g.pet.hunger=100;return g.startBattle(()=>.5,()=>1,()=>0,()=>appearance,()=>.5);}
function leave(g){g.flee();g.s.lastBattleTrainer=false;}
function win(g){const b=g.s.battle;b.player.hp=b.player.maxHp=10000;let out;while(g.s.battle){b.enemy.hp=0;out=g.endTurn([],[],()=>.5,()=>1);}g.s.pending=[];g.s.progressing=false;return out;}
test('four normal encounters then fifth is legend; wild and first ten battles do not advance cycle',()=>{const g=ready();g.s.battleCount=0;for(let i=0;i<10;i++){assert.equal(encounter(g).kind,'wild');leave(g);}assert.equal(g.s.trainerCycle,0);for(let i=0;i<4;i++){const b=encounter(g);assert.equal(b.legend,false);assert.equal(b.enemyTeam.length,3);leave(g);}const b=encounter(g);assert.equal(b.legend,true);assert.equal(b.enemyTeam.length,4);for(const e of b.enemyTeam){assert.ok(e.level>=32&&e.level<=34);assert.ok(e.heldItem);}assert.equal(g.s.trainerCycle,4);});
test('legend flee retains boss; defeat resets cycle and next trainer is normal',()=>{const g=ready();g.s.trainerCycle=4;const b=encounter(g,.2),id=b.trainerId;g.flee();assert.equal(encounter(g,.9).kind,'wild');g.flee();assert.equal(encounter(g,.9).trainerId,id);g.s.battle.player.hp=0;g.endTurn([],[],()=>.5,()=>1);assert.equal(g.s.specialShopOpen,false);assert.equal(g.s.trainerCycle,0);assert.equal(g.s.pendingLegendId,null);assert.equal(encounter(g).kind,'wild');g.flee();assert.equal(encounter(g).legend,false);assert.equal(g.s.trainerCycle,1);});
test('special legend has exactly six Grimer; rewards/unlock only after all six',()=>{const g=ready();g.s.trainerCycle=4;const b=encounter(g,.9999);assert.equal(b.trainerName,'레전드 트레이너 · 으어으어 임한규');assert.equal(b.enemyTeam.length,6);assert.ok(b.enemyTeam.every(p=>p.speciesId===88));const xp=g.pet.exp,coins=g.s.coins,total=b.enemyTeam.reduce((n,p)=>n+battleExperience(p.level),0);b.player.hp=b.player.maxHp=10000;for(let i=0;i<5;i++){b.enemy.hp=0;assert.equal(g.endTurn([],[],()=>.5,()=>1).result,null);assert.equal(g.s.specialShopOpen,false);}b.enemy.hp=0;assert.equal(g.endTurn([],[],()=>.5,()=>1).result,'win');assert.equal(g.s.specialShopOpen,true);assert.equal(g.s.coins,coins+900);assert.equal(g.pet.exp,xp+total);assert.equal(g.s.legendWins,1);assert.equal(g.battleTurnLimit(b),360);});
test('one successful purchase closes shop; invalid purchase preserves ticket and points; next cycle repeats',()=>{const g=ready();g.s.trainerCycle=4;encounter(g);win(g);assert.equal(g.s.specialShopOpen,true);g.chooseLegendReward('move');const stock=g.eggStock(()=>.5),id=stock.eggs.find(id=>!g.pet.moves.includes(id));const before=JSON.stringify(g.s);assert.throws(()=>g.teachEgg(id,99));assert.equal(JSON.stringify(g.s),before);g.teachEgg(id,0);assert.equal(g.s.specialShopOpen,false);assert.equal(g.s.trainerCycle,0);assert.throws(()=>g.teachEgg(stock.eggs[1],0));g.s.lastBattleTrainer=false;for(let i=0;i<4;i++){assert.equal(encounter(g).legend,false);leave(g);}assert.equal(encounter(g).legend,true);});
test('open shop cannot accumulate more tickets; old unlocked saves preserve exactly one purchase',()=>{const g=ready();g.s.specialShopOpen=true;for(let i=0;i<7;i++){assert.equal(encounter(g).legend,false);leave(g);}assert.equal(g.s.trainerCycle,0);g.s.trainerWins=12;delete g.s.specialShopOpen;delete g.s.trainerCycle;const old=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.equal(old.s.specialShopOpen,true);assert.equal(old.s.trainerCycle,0);old.s.pets[old.s.active].hp=10;validateState(db,old.s);const save=new Game(db,JSON.parse(JSON.stringify(old.s)));assert.equal(save.s.specialShopOpen,true);});
test('normal fifth lifetime victory does not unlock; only tagged legend wins do',()=>{const g=ready();g.s.trainerWins=4;encounter(g);win(g);assert.equal(g.s.trainerWins,5);assert.equal(g.s.specialShopOpen,false);});
test('legend team, queue and progress survive save; each opponent can be shiny and hidden',()=>{const g=ready();g.s.trainerCycle=4;g.s.fatigue=0;const b=g.startBattle(()=>.5,()=>0,()=>0,()=>.999,()=>0);assert.ok(b.enemyTeam.every(e=>e.shiny));const restored=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.deepEqual(restored.s.battle,b);assert.equal(restored.s.pendingLegendId,'im-hangyu');});
test('all 15 Elite Four sprites are local PNGs and custom legend has black SVG silhouette',()=>{assert.equal(LEGEND_TRAINERS.length,16);for(const t of LEGEND_TRAINERS){const data=fs.readFileSync(new URL('../'+t.sprite,import.meta.url));if(t.special){assert.match(data.toString(),/<svg/);assert.match(data.toString(),/#080b12/);}else assert.equal(data.subarray(1,4).toString(),'PNG');}});

test('legacy save immediately after legend defeat resets on load',()=>{const g=ready();g.s.trainerCycle=4;g.s.pendingLegendId='will';g.s.lastBattleTrainer=true;g.s.journal=[{day:1,text:'전투에서 졌어요. 다른 친구와 다시 도전하거나 회복하세요.'}];const restored=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.equal(restored.s.trainerCycle,0);assert.equal(restored.s.pendingLegendId,null);});
test('Ditto can buy a universal special move outside its learnset; one purchase closes shop',()=>{const g=ready();g.s.pets[g.s.active]=makePet(db,132,30);g.s.specialShopOpen=true;const stock=g.eggStock(()=>.5),id=stock.bonus.find(id=>!g.pet.moves.includes(id));assert.equal(stock.bonus.length,6);assert.ok(!db.pokemon[132].learnset.some(m=>m.moveId===id));const coins=g.s.coins,price=g.eggPrice(id);g.teachEgg(id);assert.ok(g.pet.moves.includes(id));assert.equal(g.s.coins,coins-price);assert.equal(g.s.specialShopOpen,false);assert.throws(()=>g.teachEgg(stock.bonus[1]));});
