import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game,makePet} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function setup(count=3){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.active=1;g.s.pets={1:makePet(db,1,30)};for(let i=2;i<=count;i++)g.s.pets[i]=makePet(db,i===2?4:7,30);g.s.battleCount=10;g.startBattle(()=>.5,()=>1,()=>0,()=>.5,()=>.5);return g;}
function faint(g){g.s.battle.player.hp=0;return g.endTurn([],[],()=>.5,()=>1);}
test('two or three party members: choose replacements and lose only after all faint',()=>{for(const n of [2,3]){const g=setup(n);for(let i=1;i<n;i++){assert.equal(faint(g).result,null);assert.equal(g.s.battle.awaitingReplacement,true);assert.equal(g.s.pets[i].hp,0);g.battleSwitch(i+1,()=>.5);}assert.equal(faint(g).result,'lose');assert.equal(g.s.battle,null);}});
test('replacement consumes no turn, enemy PP, residual damage or field duration',()=>{const g=setup(),b=g.s.battle;faint(g);b.enemy.status='poison';b.weather='sand';b.weatherTurns=4;const turn=b.turn,hp=g.s.pets[2].hp,enemy=structuredClone(b.enemy);const out=g.battleSwitch(2,()=>.5);assert.equal(out.result,null);assert.deepEqual(out.events,[]);assert.equal(b.turn,turn);assert.equal(b.weatherTurns,4);assert.equal(b.player.hp,hp);assert.equal(b.enemy.hp,enemy.hp);assert.deepEqual(b.enemy.moves,enemy.moves);assert.equal(b.awaitingReplacement,false);});
test('waiting state survives save, blocks attacks/items and rejects fainted choices',()=>{let g=setup();faint(g);g=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.equal(g.s.battle.awaitingReplacement,true);const before=JSON.stringify(g.s);assert.throws(()=>g.act(g.s.battle.player.moves[0].id));assert.throws(()=>g.battleItem('potion'));assert.throws(()=>g.battleSwitch(1));assert.equal(JSON.stringify(g.s),before);g.battleSwitch(2);assert.equal(g.s.active,2);});
test('fainted trapped Pokemon can be replaced; existing bench PP and status survive',()=>{const g=setup(),b=g.s.battle;const f=g.fighter(g.s.pets[2]);f.status='burn';f.moves[0].pp=1;b.bench={2:f};b.player.bound={turns:3};b.player.ingrain=true;faint(g);g.battleSwitch(2);assert.equal(b.player.status,'burn');assert.equal(b.player.moves[0].pp,1);});
test('entry hazard KO prompts again without extra enemy attack or residual tick',()=>{const g=setup(),b=g.s.battle;faint(g);g.s.pets[2].hp=1;g.fieldSide(b.player).stealthRock=true;const turn=b.turn;assert.equal(g.battleSwitch(2).result,null);assert.equal(b.player.hp,0);assert.equal(b.awaitingReplacement,true);assert.deepEqual(g.availableReplacements(),[3]);assert.equal(b.turn,turn);g.battleSwitch(3);assert.equal(b.awaitingReplacement,false);});
test('simultaneous faint advances trainer queue once, replacement cannot duplicate XP',()=>{const g=setup(),b=g.s.battle;b.enemy.hp=0;faint(g);assert.equal(b.enemyIndex,1);const xp=b.earnedXP;g.battleSwitch(2);assert.equal(b.enemyIndex,1);assert.equal(b.earnedXP,xp);});
test('voluntary switch still gives exactly one opposing action',()=>{const g=setup(),b=g.s.battle,turn=b.turn;let attacks=0;g.attack=()=>{attacks++;};g.battleSwitch(2);assert.equal(attacks,1);assert.equal(b.turn,turn+1);});
