import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,ITEMS,shopCatalog,battleExperience,validateState} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function ready(id=25){const g=new Game(db);g.hatch(()=>0,()=>1,()=>.5);g.s.pets[g.s.active]=makePet(db,id,20);g.s.coins=30000;return g;}
test('Gen3 plus Gen4 has 52 TMs, 43 enabled and no Substitute; compatibility respects species and ancestor',()=>{assert.equal(Object.keys(db.tms).length,52);assert.equal(Object.values(db.tms).filter(t=>t.enabled).length,43);assert.equal(db.tms['tm-24'].moveId,85);assert.equal(db.tms['tm-50'].moveId,315);assert.ok(!Object.values(db.tms).some(t=>t.moveId===164));assert.deepEqual(db.pokemon[132].tmMoves,[]);assert.equal(db.pokemon[466].tmCompatibilitySource,125);assert.deepEqual(db.pokemon[466].tmMoves,db.pokemon[125].tmMoves);for(const [id,t] of Object.entries(db.tms))assert.equal(!!shopCatalog(db)[id],t.enabled);});
test('TM price increases with effective power; status has explicit fixed price',()=>{const attacks=Object.values(db.tms).filter(t=>t.enabled&&db.moves[t.moveId].damageClass!=='status');for(const a of attacks)for(const b of attacks)if(a.effectivePower<b.effectivePower)assert.ok(a.price<b.price);assert.equal(db.tms['tm-04'].price,600);assert.ok(db.tms['tm-15'].price>db.tms['tm-24'].price);});
test('shiny item requires 20k points, is single-use and preserves ability level moves HP',()=>{const g=ready();g.pet.abilitySlot=3;g.s.coins=19999;const before=JSON.stringify(g.s);assert.throws(()=>g.buy('shiny-stone'));assert.equal(JSON.stringify(g.s),before);g.s.coins=20000;g.buy('shiny-stone');assert.equal(g.s.coins,0);const pet=structuredClone(g.pet);g.makeShiny();assert.deepEqual(g.pet,{...pet,shiny:true});assert.equal(g.s.inventory['shiny-stone'],0);g.s.inventory['shiny-stone']=1;const saved=JSON.stringify(g.s);assert.throws(()=>g.makeShiny());assert.equal(JSON.stringify(g.s),saved);assert.equal(new Game(db,validateState(db,JSON.parse(saved))).pet.shiny,true);});
test('shiny item is never in drop pool and battle blocks item use',()=>{const g=ready();for(const id of Object.keys(shopCatalog(db)))g.s.inventory[id]=999;g.s.inventory['shiny-stone']=0;assert.equal(g.rollDrop([],()=>0),null);assert.equal(g.s.inventory['shiny-stone'],0);g.s.inventory['shiny-stone']=1;g.startBattle(()=>.5,()=>1,()=>1,()=>0,()=>.5);const before=JSON.stringify(g.s);assert.throws(()=>g.makeShiny());assert.equal(JSON.stringify(g.s),before);});
test('TM purchase and replacement consume exactly one, invalid slots and incompatible species consume nothing',()=>{const g=ready();g.pet.moves=[84,86,98,45];g.buy('tm-24',2);const coins=g.s.coins,raw=JSON.stringify(g.s);assert.throws(()=>g.teachTM('tm-24'));assert.throws(()=>g.teachTM('tm-24',4));assert.equal(JSON.stringify(g.s),raw);g.teachTM('tm-24',2);assert.deepEqual(g.pet.moves,[84,86,85,45]);assert.equal(g.s.inventory['tm-24'],1);assert.equal(g.s.coins,coins);const after=JSON.stringify(g.s);assert.throws(()=>g.teachTM('tm-24',0));assert.equal(JSON.stringify(g.s),after);const ditto=ready(132);ditto.s.inventory['tm-24']=1;const save=JSON.stringify(ditto.s);assert.throws(()=>ditto.buy('tm-24'));assert.throws(()=>ditto.teachTM('tm-24',0));assert.throws(()=>ditto.buy('tm-16'));assert.equal(JSON.stringify(ditto.s),save);});
test('TM fills an empty slot, survives save/evolution and cannot be used in battle',()=>{const g=ready();g.pet.moves=[84];g.buy('tm-24',2);g.teachTM('tm-24');assert.deepEqual(g.pet.moves,[84,85]);g.evolveTo(26);const restored=new Game(db,validateState(db,JSON.parse(JSON.stringify(g.s))));assert.ok(restored.pet.moves.includes(85));assert.equal(restored.s.inventory['tm-24'],1);g.startBattle(()=>.5,()=>1,()=>1,()=>0,()=>.5);assert.throws(()=>g.teachTM('tm-24',0));});
test('XP is 60% of previous award, without reducing existing accumulated XP',()=>{for(const [lv,expected] of [[7,89],[20,595],[50,3619]])assert.equal(battleExperience(lv),expected);const g=ready();const xp=g.pet.exp;const restored=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.equal(restored.pet.exp,xp);assert.equal(restored.pet.level,20);});
test('Overheat lowers user Special Attack, Steel Wing raises user Defense, Facade doubles power',()=>{const g=ready(4),p=g.fighter(g.pet),e=g.fighter(makePet(db,129,20));p.hp=e.hp=p.maxHp=e.maxHp=10000;g.s.battle={player:p,enemy:e,turn:1};p.moves=[{id:315,pp:5},{id:211,pp:25},{id:263,pp:20}];g.execute(p,e,315,[],()=>.5);assert.equal(p.stages['special-attack'],-2);assert.equal(e.stages['special-attack'],0);g.execute(p,e,211,[],()=>.05);assert.equal(p.stages.defense,1);assert.equal(e.stages.defense,0);let hp=e.hp;g.execute(p,e,263,[],()=>.5);const normal=hp-e.hp;p.status='poison';hp=e.hp;g.execute(p,e,263,[],()=>.5);assert.ok(hp-e.hp>normal*1.8);});
