import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game,makePet,TRAINER_CHANCE,battleExperience,validateState} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));
function ready(){const g=new Game(db);g.hatch(()=>0,()=>1);g.s.pets[g.s.active]=makePet(db,172,20);return g;}
function reset(g){g.flee();g.s.fatigue=0;g.pet.hunger=100;}
function trainer(){const g=ready();g.s.battleCount=10;g.startBattle(()=>.5,()=>0,()=>0);return g;}
test('first ten battles never trigger trainer; eleventh can and next must be wild even after fleeing',()=>{const g=ready();for(let n=1;n<=10;n++){assert.equal(g.startBattle(()=>.5,()=>1,()=>0).kind,'wild');assert.equal(g.s.battleCount,n);reset(g);}assert.equal(g.startBattle(()=>.5,()=>1,()=>0).kind,'trainer');reset(g);assert.equal(g.startBattle(()=>.5,()=>1,()=>0).kind,'wild');reset(g);assert.equal(g.startBattle(()=>.5,()=>1,()=>0).kind,'trainer');});
test('20 percent threshold and independent shiny rolls; all three levels are strictly lower',()=>{assert.equal(TRAINER_CHANCE,.2);for(const [r,kind] of [[.199999,'trainer'],[.2,'wild']]){const g=ready();g.s.battleCount=10;assert.equal(g.startBattle(()=>.5,()=>1,()=>r).kind,kind);}for(const r of [0,.5,.99999]){const g=ready();g.s.battleCount=10;let n=0;const b=g.startBattle(()=>r,()=>[.039,.04,.9][n++],()=>0);assert.equal(b.enemyTeam.length,3);assert.deepEqual(b.enemyTeam.map(p=>p.shiny),[true,false,false]);for(const p of b.enemyTeam)assert.ok(p.level<20&&p.level>=17);}});
test('trainer queue preserves player HP PP and status; rewards only after third opponent',()=>{const g=trainer(),b=g.s.battle;const total=b.enemyTeam.reduce((n,p)=>n+battleExperience(p.level),0),money=g.s.coins,xp=g.pet.exp;b.player.moves[0].pp=1;b.player.status='paralysis';const hp=b.player.hp;for(let i=0;i<2;i++){b.enemy.hp=0;const out=g.endTurn([],[]);assert.equal(out.result,null);assert.equal(b.enemyIndex,i+1);assert.equal(b.player.hp,hp);assert.equal(b.player.moves[0].pp,1);assert.equal(b.player.status,'paralysis');assert.equal(g.s.coins,money);assert.equal(g.pet.exp,xp);}b.enemy.hp=0;assert.equal(g.endTurn([],[]).result,'win');assert.equal(g.s.battle,null);assert.equal(g.s.coins,money+240);assert.equal(g.pet.exp,xp+total);});
test('trainer balls cannot be consumed and saving restores exact queue and encounter history',()=>{const g=trainer();const state=JSON.stringify(g.s);assert.throws(()=>g.battleItem('poke-ball'),/트레이너/);assert.equal(JSON.stringify(g.s),state);const restored=new Game(db,JSON.parse(state));assert.deepEqual(restored.s.battle,g.s.battle);assert.equal(restored.s.battleCount,11);reset(restored);assert.equal(restored.startBattle(()=>.5,()=>1,()=>0).kind,'wild');});
test('loss never sends next opponent, fails without rewards; invalid start never counts',()=>{const g=trainer();const coins=g.s.coins;g.s.battle.player.hp=0;g.s.battle.enemy.hp=0;assert.equal(g.endTurn([],[]).result,'lose');assert.equal(g.s.coins,coins);const count=g.s.battleCount;assert.throws(()=>g.startBattle());assert.equal(g.s.battleCount,count);});
test('legacy saves start counter at zero; release preserves counter and level one cannot meet lower trainer',()=>{const g=ready();delete g.s.battleCount;delete g.s.lastBattleTrainer;validateState(db,g.s);const upgraded=new Game(db,JSON.parse(JSON.stringify(g.s)));assert.equal(upgraded.s.battleCount,0);upgraded.s.battleCount=11;upgraded.s.lastBattleTrainer=true;upgraded.release();assert.equal(upgraded.s.battleCount,11);assert.equal(upgraded.s.lastBattleTrainer,true);const low=ready();low.s.pets[low.s.active]=makePet(db,172,1);low.s.battleCount=10;assert.equal(low.startBattle(()=>0,()=>1,()=>0).kind,'wild');});
