import {FIELD_INFO} from '../field.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {Game,makePet,shopCatalog,ITEMS,medicineUsable,statsFor,captureChance,abilityItemTarget} from '../engine.js';
const db=JSON.parse(fs.readFileSync(new URL('../data/pokedex.json',import.meta.url)));const code=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
function setup(){const game=new Game(db);game.hatch(()=>0,()=>1,()=>.5);game.s.pets[game.s.active]=makePet(db,25,20);const nodes={};const ctx=vm.createContext({FIELD_INFO,db,game,busy:false,tmQuery:'',shopCatalog,ITEMS,medicineUsable,statsFor,captureChance,abilityItemTarget,closeModal(){},save(){},render(){},say(){},$:id=>nodes[id]??=( {querySelectorAll:()=>[]} ),modal:html=>{ctx.output=html;}});
 const esc=code.slice(code.indexOf('const esc='),code.indexOf('const wait='));const colors=code.slice(code.indexOf('const typeColors='),code.indexOf('let db,game'));const helpers=code.slice(code.indexOf('const typeSkin='),code.indexOf('const petSprite='));const shops=code.slice(code.indexOf('const itemKindLabel='),code.indexOf('function showDex('));vm.runInContext(esc+colors+helpers+shops,ctx);return {ctx,game};}
test('TM learning shows the new move and all four explicit replacement choices',()=>{const {ctx,game}=setup();assert.equal(game.pet.moves.length,4);vm.runInContext("teachTMDialog('tm-24')",ctx);assert.ok(ctx.output.includes('새로 배울 기술'));assert.ok(ctx.output.includes('10만볼트'));assert.ok(ctx.output.includes('10% 확률로 마비'));assert.equal((ctx.output.match(/data-tm-slot=/g)||[]).length,4);assert.equal((ctx.output.match(/이 기술을 잊고/g)||[]).length,4);});
test('TM shop explains effect and insufficient points without hiding prices for available purchases',()=>{const {ctx,game}=setup();game.s.coins=0;vm.runInContext('showTMShop(false)',ctx);assert.ok(ctx.output.includes('P 부족'));assert.ok(ctx.output.includes('tm-rules'));assert.ok(ctx.output.includes('특수공격 1단계 상승'));assert.ok(!ctx.output.includes('undefined'));});
test('bag explains why balls and medicines are unavailable and held filter opens correctly',()=>{const {ctx,game}=setup();game.s.inventory={'poke-ball':2,potion:1,'quick-claw':1};vm.runInContext('showBag()',ctx);assert.ok(ctx.output.includes('야생 전투 중 사용할 수 있어요'));assert.ok(ctx.output.includes('회복할 HP·상태이상이 없어요'));vm.runInContext("showBag(false,'held')",ctx);assert.ok(ctx.output.includes('선제공격손톱'));assert.ok(!ctx.output.includes('data-use="potion"'));game.s.battle={kind:'trainer',player:game.fighter(game.pet),enemy:game.fighter(makePet(db,129,10))};vm.runInContext('showBag(true)',ctx);assert.ok(ctx.output.includes('트레이너의 포켓몬은 포획할 수 없어요'));assert.ok(!ctx.output.includes('undefined'));});
test('egg shop renders lock progress, legal offers, six daily slots and explicit replacement choices',()=>{const {ctx,game}=setup();const extra=code.slice(code.indexOf('function renderFieldPanel'),code.indexOf('function renderTrainerBanner'));vm.runInContext(extra,ctx);vm.runInContext('showEggShop()',ctx);assert.ok(ctx.output.includes('0 / 5번째 도전'));game.s.trainerWins=5;game.s.specialShopOpen=true;game.s.coins=50000;game.pet.speciesId=1;vm.runInContext('showEggShop()',ctx);assert.ok(ctx.output.includes('특별 기술 6/6'));assert.ok(!ctx.output.includes('undefined'));const id=game.eggStock().eggs.find(id=>!game.pet.moves.includes(id));vm.runInContext(`eggTeachDialog(${id})`,ctx);assert.equal((ctx.output.match(/data-egg-slot=/g)||[]).length,4);assert.ok(ctx.output.includes('성공할 때만 차감'));});
